# -*- coding: utf-8 -*-
"""Story: The red emergence
"""
import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '../..'))
sys.path.append('storybuilder')

from storybuilder.builder import world as wd
from src.emergence import config as cnf
THM = cnf.THEMES


# scenes
def sc_redmoon(w: wd.World):
    miyako, aya = w.miyako, w.aya
    return w.scene("赤い月",
            w.tag.comment("美耶古の三人称視点／心理描写使わない（画面描写オンリー）"),
            miyako.look("遠い世界の空で",
                "それは濃いオレンジのような赤を滾らせて鈍く闇に存在していた"),
            miyako.look("$n_miyakoが今見ているスマートフォンの画面には",
                "小学校以来の親友から送られたアメリカ西海岸の皆既月食の空が映っていた。",
                "家族旅行でわざわざそれを見るツアーに申し込んだのだと",
                "年末に嬉しそうに話してくれたことを思い出す"),# NOTE:思い出す
            miyako.talk("でも結局自分の写真は一枚も送ってこないじゃない。",
                "あのばーか"),
            miyako.deal("ベッドの上で寝返りを打ち",
                "天井に向かってスマホを持つと",
                "ＬＩＮＥアプリを呼び出して",
                "今ならひょっとすると出てくれるかも知れない",
                "という一縷の望みでコールを押した"),
            miyako.look("彼女", "$n_ayaの名前が表示されたまま",
                "コール音がただただ部屋に鳴り響く"),
            miyako.hear("一回", "二回三回……"),
            miyako.look("何も変化がないままコールを終えると",
                "彼女からの新しいＬＩＮＥ通知に気づいて$Sは画面をタップする"),
            aya.talk().emphasis("ブラッドムーンて言うんだって", "皆既月食"),
            miyako.deal("今年に入って初めての$ayaの言葉に慌てて返事を打ち込もうとしたが",
                "すぐに現れた次の文章に目を奪われて", "人差し指を向けたまま$Sは固まった"),
            aya.talk().emphasis("一度消えて生まれ変わる為には",
                "血を流さないといけないんだね"),
            miyako.talk("$aya？"),
            miyako.deal("すぐに「大丈夫」とか「そんなことない」とか薄っぺらな言葉を幾つも並べたけれど",
                "既読もないまま", "ただ$Sの吹き出しだけがずらりと画面を覆い尽くした"),
            # TODO: 虫（蜘蛛）、美耶古の外見情報
            miyako.be(w.stage.myroom),
            miyako.deal("そしてその言葉を最後に",
                "彼女からは一切返信がなくなってしまった"),
            )

def sc_hermother(w: wd.World):
    miyako, kikyo = w.miyako, w.kikyo
    return w.scene("彼女の母",
            miyako.go(w.stage.ayahome, w.day.vanishnext),
            kikyo.talk("ごめんなさい。", "あの子部屋から出てこなくて"),
            miyako.reply("わかりました"),
            miyako.think("彼女の母はちょっと変わった人で苦手だった"),
            miyako.look("知らない女性が入れ替わりに入って行った"),
            miyako.think("けれど翌日も次の日もずっと",
                "$ayaとは連絡がつかないままだった"),
                w.miyako.look(w.aya, w.i.herstatus),
                w.miyako.think(w.aya, w.i.herrefusal),
            ).omit()

def sc_boringday(w: wd.World):
    miyako, kiri = w.miyako, w.kirimura
    return w.scene("退屈な日々",
            miyako.be(w.stage.classroom, w.day.valentain),
            miyako.hear("先生の言葉がどんどんすりぬけていく"),
            miyako.think("あれからずっと$ayaと連絡が取れない。",
                "家にも入れてもらえない。",
                "ただＬＩＮＥの既読だけが細い糸のような繋がりだった"),
            miyako.remember("そういえば$ayaが美術部だったことを思い出す"),
            ).omit()

def sc_strangeman(w: wd.World):
    miyako, kiri = w.miyako, w.kirimura
    return w.scene("妙な先生",
            miyako.move("春休みに入った高校は",
                "グラウンドで練習する陸上部や野球部の掛け声が響くくらいで",
                "何とも物静かだ"),
            miyako.move("ひんやりとした廊下の上",
                "紺色のセーラー服のスカートを蹴り上げるように歩きながら",
                "$Sは教務棟の二階の視聴覚室脇を通り過ぎる"),
            miyako.look("蛍光灯の照らさない薄暗い廊下には他の部屋から漏れる陽光が入らず",
                "ただ突き当りの窓だけが強く光っている。",
                "それは長い長いトンネルのようにも見えたが",
                "$Sはその光源までに足を止めると",
                "唯一明かりが点いていた部屋の戸を軽く開けた"),
            miyako.ask("失礼します"),
            miyako.come(w.stage.artroom,
                "見上げたプレートには『美術室』とあったが",
                "そこに手書きの紙が張り付けられて『準備室』と続いている"),
            miyako.look("生徒の作品だろうか。",
                "部屋に入るとイーゼルに置かれたものやそうでないものを含めて",
                "無数の油絵が散乱していた"),
            miyako.feel("鼻を突くシンナーのような臭いに思わず口元を押さえる"),
            miyako.look("けれど口を押さえたのはそれだけではなかった。",
                "赤や青で汚れた白衣を着た男性が足元に転がっていたからだ"),
            miyako.talk("ひゃっ！"),
            kiri.ask("なんだ？"),
            miyako.look("のそりと顔を上げたのは美術部顧問の$kirimura先生のはずだが",
                "前に見た時よりも無精髭が酷く",
                "目は虚ろで",
                "青い絵の具でも塗りたくればゾンビ映画に出ても遜色ないくらいだった"),
            kiri.talk("ちょっとクラっと来てな"),
            miyako.look("廊下側も外側も窓が閉め切られたままだ"),
            miyako.talk("本当に美術の先生なんですか？"),
            miyako.deal("キャンバスやイーゼルのパーツ", "石膏像に画材で埋まっている外側の窓は放っておいて",
                "$Sは急いで廊下側の窓を全て開け放つ。",
                "ついでに倒れていた扇風機をコンセントに差し込み", "最強で回した"),
            miyako.talk("ちょっと飲み物買って来るんで"),
            miyako.move("何とか上半身を起こした先生を見てそう言うと",
                "$Sは一番近い階段下の自販機まで走った"),
            )

def sc_herdrawing(w: wd.World):
    miyako, kiri = w.miyako, w.kirimura
    return w.scene("彼女の絵",
            kiri.talk("生き返るとはこういう気分だったのか"),
            miyako.talk("何ばかなこと言ってるんですか"),
            miyako.look("背もたれのない木椅子に座り",
                "猫背で肩を揺らして笑う$kirimuraの姿に", "$Sはつい腕組みをしてしまう"),
            kiri.ask("それで春休みなのに何か用か？",
                "$miyakoは美術部でもなかったろ"),
            miyako.talk("先生は部員だった$n_ayaのこと", "覚えてますか？"),
            miyako.look("軽く頷くと「ちょっと待ってろ」と",
                "$kirimura先生はイーゼルとキャンバスの海に分け入っていく"),
            miyako.ask("何なんですか？"),
            miyako.look("質問を無視したまま何かに没頭する姿に少しだけ$ayaを重ねてみたが",
                "「あった」と宝物でも見つけたみたいに得意げな表情をして一枚の絵を手にした彼は",
                "$Sの方に戻ってくる。",
                "描き掛けの風景画が掛かっていたイーゼルから投げるようにキャンバスを退かすと",
                "その絵を立てて$Sによく見えるように角度を変えた"),
            kiri.talk("$ayaの絵だ"),
            miyako.look("それは赤い海なのか空なのか",
                "その背景に浮かぶ月と", "それを目指して手を伸ばす裸に見える女性が赤いシルエットで描かれたものだった"),
            miyako.look("あまりの赤に$Sは言葉を失う"),
            kiri.talk("彼女は夏休み前に入部してそれから約二ヶ月掛けてこの絵を仕上げ",
                "それ以来部活動には顔を出さなくなった"),
            miyako.talk("不登校になったからです"),
            miyako.look("知らなかったのか$kirimuraは目を大きくして$Sを見ると「そうか」と小さく唇を動かした"),
            miyako.talk("クラスは別だったので$meも聞いた話しか知りません。",
                "端的に言えば",
                "$ayaはいじめられていました"),
            kiri.talk("美人だったからか？"),
            miyako.look("冗談のつもりではないのだろう。",
                "真剣な眼差しでの質問に$Sは苦笑して首を振り", "続ける"),
            miyako.talk("確かに小学校からよく男子にはモテていて",
                "そのことで他の女子からやっかみを受けたり",
                "時には鞄をゴミ箱に投げ込まれたりしたこともありましたけど",
                "そんなことで学校に来なくなるような子ではなかったんです"),
            miyako.look("$kirimuraはじっと黙って話に耳を傾けながら",
                "ペットボトルのお茶の残りを喉へ流し込む"),
            miyako.talk("実は彼女の母親がある宗教の教祖だという噂が流れて",
                "それで色々とあることないこと", "全てを彼女の所為にされていたそうです"),
            miyako.look("宗教。",
                "そう口を動かしただけで先生はじっと$Sを見ている"),
            miyako.talk("聞いたことありませんか？",
                "$religion"),
            kiri.reply("いや"),
            miyako.talk("最近ラジオでＣＭを流しているのを聞きました。",
                "月の満ち欠けとバイオリズムがどうとか", "言ってましたけど"),
            kiri.ask("少なくとも$meは$n_ayaという生徒がいじめを受けて不登校になったという話を",
                "職員会議なんかで聞いていない"),
            miyako.hear("$kirimuraの口から「職員会議」という言葉が出た瞬間に思わず口を押さえて笑いを隠したが",
                "$Sは「わかってます」と答え", "更に続けた"),
            miyako.talk("$meもいじめが原因とは考えていません。",
                "そもそも夏休み前から彼女", "様子がおかしかったんです。",
                "$meが誘っても忙しいと答えてくれなくなったし",
                "ニ学期になって学校に来なくなると",
                "ＬＩＮＥにもほとんど反応しなくなりました"),
            kiri.ask("それは$miyakoとの間で何かあったんじゃないのか？"),
            miyako.look("先生は空になったペットボトルのキャップを締めながら",
                    "眉根を寄せて尋ねる"),
            kiri.talk("絵というものは描く人間の心の中の投影でもある。",
                    "これを見て",
                    "$miyakoは何を感じる？"),
            miyako.look("まるで赤い墨で描かれた水墨画にも見える$ayaの絵は",
                    "じっと見ているうちに月が溶け出してそれが糸を引いて流れ落ちた先に手を上げる女性として生まれ変わっているようにも見える"),
            miyako.talk("実は彼女",
                    "何度かＬＩＮＥでこんなことを言ってきたんです。",
                    "『新しい自分に今すぐ生まれ変わりたい』って。",
                    "先生は何か心当たりがあったりしませんか？"),
            miyako.look("いや", "と軽く首を振ると続けてこう言った"),
            kiri.talk("$meはそこまで部活に顔を出してた訳じゃないが",
                    "$ayaに特別そういった何かを感じたということはない。",
                    "寧ろあいつは自分のことが意外と気に入っているんじゃないかと思ってたくらいだ"),
            miyako.talk("そうです。",
                    "$meもそう思うんです。",
                    "だからこそどうしてって"),
            kiri.ask("なあ$miyako。",
                    "$meは$ayaから消しゴムを借りていて",
                    "それを返す必要があるんだ"),
            miyako.look("にやり", "としながらそう言った$kirimuraの意図が分からずに首を捻ったが",
                    "彼は「返す必要がある」と繰り返しただけだった"),
            )

def sc_herhome(w: wd.World):
    miyako, kiri, kikyo = w.miyako, w.kirimura, w.kikyo
    return w.scene("彼女の家",
            miyako.look("$ayaの家の玄関前で",
                "$kirimura先生がインタフォンを押してもそもそ言っているのを$Sは後ろから黙って見ていた。",
                "二階の彼女の部屋は窓もカーテンも閉め切られていて", "薄暗い"),
            miyako.go(w.stage.ayahome),
            kiri.ask("すみません。", "$st_highschoolの$ln_kirimuraですが。",
                "$n_ayaさん", "いらっしゃいませんか？"),
            miyako.look("先生は振り返って$Sに眉を顰めて見せる"),
            miyako.talk("ずっとこうなんです。",
                "一月にアメリカに皆既月食を見に行くと連絡があって",
                "それから一度も誰か応対に出てくれるということがなかったんです"),
            kiri.talk("母親か父親の仕事先は？"),
            miyako.talk("$meは知らなくて。",
                "それに父親の方は$ayaが中学の時に離婚しています"),
            miyako.look("そうか。",
                "と低い声で頷いて",
                "それでも$kirimuraは何度かインタフォンを押した。",
                "だが誰かが出てくる様子はなく",
                "家の中で物音の一つも響かない"),
            kiri.talk("なあ$miyako……これ", "開くぞ"),
            miyako.ask("え？",
                "$meが昨日来た時は鍵が掛かってましたよ？"),
            miyako.look("$Sに静かに頷くと",
                "$kirimuraは慎重にドアを開ける"),
            miyako.talk("$aya？"),
            kiri.talk("しっ"),
            miyako.look("声を出そうとした$Sに", "先生は人差し指を立てた"),
            kiri.talk("何か……臭う"),
            miyako.look("弛緩していた表情筋の全てが緊張したような彼の様子に",
                "$Sは黙って頷くとその背に続いた"),
            )

def sc_gotoherroom(w: wd.World):
    miyako, kiri, kikyo = w.miyako, w.kirimura, w.kikyo
    return w.scene("彼女の部屋に",
            miyako.look("先生から靴は脱ぐなと言われたが",
                "意味が理解できず", "$Sはスリッパを出してそれに足を通した"),
            miyako.look("約十年ぶりに入った$ayaの家は電気を点けていないからか",
                "不気味な薄暗さが続いていた。",
                "玄関の靴箱の上にはアフリカのどこかの国のお土産品のような手足の捻れた土人形が飾られ",
                "上がり框に敷かれたマットは小さな仏像が並んで描かれた曼荼羅と呼ぶのだろうか",
                "そんな模様に編まれたもので",
                "気づいた$Sは思わず声を上げて慌てて飛び退いた"),
            miyako.look("通路の壁にも以前はなかった大小様々な風景画が掛かっていて",
                "中の一つは真っ赤な月だけが描かれた", "$ayaの絵を少し連想させるものだった"),
            kiri.ask("$ayaの部屋は二階か？"),
            miyako.behav("はい"),
            miyako.look("声を出さずに返事をしたのを見て",
                "$kirimuraは慎重に階段を登り始める"),
            miyako.move("傾斜の急な階段は一歩一歩を気をつけて歩かないと",
                "すぐに足を踏み外してしまいそうだ"),
            miyako.feel("むっとした空気が粘り気を含んでいるみたいで",
                "$Sは込み上げた気持ち悪さに口元を押さえた"),
            kiri.talk("臭いが強くなった"),
            miyako.look("二階に辿り着くなりそう言うと",
                "$kirimuraは何かを探すように左右を確認する"),
            miyako.ask("先生？"),
            kiri.talk("なあ$miyako。",
                "お前$ayaとはＬＩＮＥができるんだったよな？"),
            miyako.reply("ええ。そうですけど"),
            kiri.talk("それなら今ちょっとだけ送ってみてくれないか"),
            miyako.deal("$kirimuraの意図がよく読めなかったが",
                "それでも「分かりました」と答えると$Sはスマートフォンを取り出す"),
            miyako.look("暗い通路を明るくしたその画面に$ayaの文字が浮かび上がると",
                "何を書こうか一瞬迷った末に",
                "ただ『どう？』とだけ書いて送った"),
            miyako.look("すぐに既読が付く"),
            miyako.deal("今", "$ayaんち来てる"),
            miyako.look("それも既読になる"),
            kiri.ask("つまり今このドアの向こう側で$ayaはそいつを見ているんだな？"),
            miyako.reply("部屋にいるんだった", "ですけど"),
            miyako.look("漢字で『$fn_aya』と書かれたプレートが下がったドアのノブを",
                "$kirimuraが掴む"),
            miyako.talk("$aya", "ねえ……いるの？"),
            miyako.hear("思わず声を上げたが", "当然何も返事はない"),
            )

def sc_transformed(w: wd.World):
    miyako, kiri, kikyo, aya = w.miyako, w.kirimura, w.kikyo, w.aya
    return w.scene("彼女の変身",
            w.miyako.come(w.stage.ayaroom, w.day.discover1),
            miyako.look("先生は$Sを振り返ることなくドアを開けた"),
            miyako.feel("刹那",
                "むっとする重い空気に押し出される粉っぽいそれが鼻先を掠めていく"),
            miyako.look("部屋はカーテンが閉め切られ",
                "真っ暗になっていた。",
                "明かりは$Sが手にしたスマートフォンの光だけで",
                "それを翳すと白い靄に覆われているのかと思うほどの",
                "細かな白い埃が舞っているのが分かった"),
            miyako.talk("$aya？"),
            kiri.talk("$miyako", "待て"),
            miyako.look("一歩前に出た$Sの腕を$kirimuraが掴む。",
                "けれど彼女は自分の手にした光源が照らし出すその奇妙なシルエットに目が釘付けになっていた"),
            miyako.talk("$aya……なの？"),
            miyako.look("ベッドの上", "と思われる場所にその何かは浮かぶようにして存在していた。",
                "よく見ればそれから出た何本もの筋が天井や壁に張り付いて支えているのが分かるのだが",
                "最初はそこにある細長い卵状のものに目を囚われて",
                "ただ浮いているようにしか見えなかった"),
            miyako.look("巨大な抱き枕",
                "あるいはドラキュラなんかを閉じ込めておく棺桶に白い布を被せたような",
                "何かが", "そこに存在している"),
            kiri.talk("こいつは……"),
            miyako.talk("$aya？",
                "そこにいるのは$ayaじゃないの？"),
            miyako.look("掴まれていた左手を振り切ると",
                "$Sはその白い何かに近づこうと部屋に踏み入ったが",
                "すぐに足元に何か転がっていることに気づいた"),
            miyako.talk("何", "これ"),
            miyako.look("カーペットの上を蜘蛛の糸のようなものが覆い尽くしていたが",
                "そこに不自然に浮かび上がる横たわったモノが",
                "彼女の右足の先に触れる"),
            miyako.look("手",
                "だろうか"),
            miyako.look("包帯でぐるぐる巻きにされたような何かが",
                "床に落ちている"),
            miyako.deal("$Sはスマートフォンを手に屈み込み",
                "それにゆっくりと手を伸ばした"),
            kiri.talk("やめろ$miyako！"),
            miyako.ask("え？"),
            miyako.deal("触れた先から",
                "真っ白な糸の塊が飛び出してきて",
                "$Sの右腕にくるくると巻き付いていく"),
            miyako.talk("イヤ！"),
            kiri.talk("$miyako！"),
            miyako.talk("先生！"),
            miyako.look("すぐに$kirimuraが靴の踵で床に押さえつけ",
                "$Sの腕から絡まり付く糸を引き剥がそうとするが",
                "剥がれるどころかどんどん新しい糸が飛び出してきては巻き付き",
                "やがて腕ごと引き摺られてベッドの脇まで転がった"),
            aya.talk("ナンデ"),
            miyako.hear("不意に響いた$ayaの声に",
                    "$Sは彼女を探した"),
            aya.talk("ナンデナノ？"),
            miyako.look("声がしたのは自分の右手から",
                    "つまりスマートフォンからだった"),
            miyako.talk("$aya！"),
            aya.talk("ドウシテ",
                    "放ッテオイテ", "クレナイノ！"),
            miyako.talk("だって$meたち",
                    "親友だったでしょ？"),
            miyako.look("引っ張られたままの右手に向かって叫んだが",
                    "大きく開けた口に次々とうどんのようになった白い糸が飛び込んできて",
                    "声も息も奪われる"),
            miyako.look("それどころか$Sの顔にも際限なく糸のシャワーが襲ってきて",
                    "すぐに視界は闇に染まった"),
            w.miyako.look(w.aya, w.sanagi),
                w.miyako.look(w.kirimura, w.i.hercause),
                w.miyako.think(w.i.rescue_aya),
                w.miyako.meet(w.aya),
                w.miyako.know(w.i.ijime),
                w.miyako.go(w.kikyo),
            )

def sc_othergirls(w: wd.World):
    miyako, kiri = w.miyako, w.kirimura
    return w.scene("蛹の少女たち",
            miyako.think("その後",
                "学校で不登校だった生徒が一斉に調べられ",
                "この学校だけで五名の生徒が繭化しているのが発見された"),
            miyako.come(w.stage.artroom),
            miyako.ask("あの", "先生？"),
            kiri.talk("これ見てみろ"),
            miyako.look("そこにあったのは先日まで$ayaが描いていたキャンバスだった"),
            miyako.look("今はそこに赤く咲いた少女たちが描かれていた"),
            kiri.talk("妙だと思って剥がしたらこれが出てきた"),
            miyako.ask("あの", "実は"),
            miyako.think("$meはずっと参加を促されていたＬＩＮＥグループの話をした"),
            kiri.talk("ちょっと預からせてくれないか？"),
            ).omit()

def sc_catchmyheart(w: wd.World):
    miyako = w.miyako
    mam, dad, sis = w.mam, w.dad, w.sister
    return w.scene("囚われる心",
            miyako.be(w.stage.myhome),
            # TODO: 家族の食卓、野木さんの母がおかしい、宗教？
            ).omit()

def sc_crazy(w: wd.World):
    miyako = w.miyako
    return w.scene("狂った女",
            # TODO: 壊れている野木、桔梗の話
            ).omit()

def sc_rebirth(w: wd.World):
    miyako, kikyo = w.miyako, w.kikyo
    return w.scene("生まれ変わる",
            ).omit()

def sc_mymind(w: wd.World):
    miyako, kikyo, kiri, aya = w.miyako, w.kikyo, w.kirimura, w.aya
    return w.scene("私の気持ち",
                w.miyako.know(w.i.aya_mind),
                w.miyako.meet(w.kikyo),
                w.miyako.look(w.aya_letter),
                w.aya.do(w.i.rebirth),
            miyako.hear("冷たい", "と感じるような水音だった"),
            miyako.look("$Sが体が丸めたままゆっくりと目を開けると",
                "殆ど光のない",
                "海の底のような場所に",
                "自分がどんどん落ちていくのが分かった"),
            miyako.look("ぼんやりとした赤い光がどんどん遠くなり",
                "手を伸ばしても誰も掴んではくれない"),
            miyako.deal("口を開くと肺から押し出された空気が気泡を作って昇っていった"),
            miyako.behav("$Sは覚悟をしたように目を閉じる"),
            miyako.feel("と",
                "その手が誰かに掴まれた"),
            miyako.look("目を開けると",
                "そこにはセーラー服姿の$n_ayaがいて",
                "「何びっくりした顔してるの？」と笑っていた"),
            miyako.talk("え？",
                "だって"),
            miyako.look("言われてから慌てて周囲を確認したが",
                "どこにも水なんてなく",
                "$ayaの部屋の中でもなく",
                "そこは小さい頃に二人でよく遊んだ公園のブランコだった"),
            aya.talk("$miyakoは制服よく似合っていて良いよね"),
            miyako.look("チェーンを両脇で抱え込むようにしながら",
                "$ayaは小さくそれを揺らす"),
            miyako.ask("似合ってるのは$ayaの方だよ。",
                "すらっと脚も長くて", "色白で",
                "みんなが羨んでる"),
            miyako.deal("$Sの方は足をぶらつかせるだけで",
                "昔からあまり揺らすのは好きじゃなかった"),
            aya.talk("$meはこの服が", "嫌い"),
            miyako.hear("そう言うと胸元を締める赤いタイが弾けるように飛んで",
                "彼女の制服が赤く染まった"),
            aya.talk("いつも何かを強いられているような窮屈さを感じていて",
                "ある日その正体が何なのか分かったの"),
            miyako.ask("$aya？",
                "両親が離婚してから何か変だよ？"),
            aya.talk("離婚は関係ないの。",
                "あれは母と父の問題。",
                "$miyakoはずっと気づかないままなんだろうな。",
                "$meたちは色々な可能性を毟り取られながら大人になる。",
                "学校に行くなんて",
                "毎日自傷行為をしているようなものだって"),
            miyako.look("彼女の制服から",
                "鮮血のような綺麗な赤が滴っていた"),
            miyako.ask("$aya？"),
            miyako.look("その赤が足元に水たまりを作り",
                "それがどんどん広がっていく"),
            aya.talk("$meは",
                    "汚れてしまった。",
                    "だから",
                    "生まれ変わって綺麗になるの"),
            miyako.ask("何言ってるか",
                    "よく分かんないよ"),
            miyako.look("やがてそれは公園だけでなくどこまでも無限の赤い水面となり",
                    "海のように波立った"),
            miyako.look("彼女はブランコを降りてそこに立つ"),
            miyako.ask("ねえ。",
                    "もう帰ろう？"),
            miyako.look("見上げた空はもう夕方だと思ったが",
                    "それは不自然なほど赤く染まっていた。",
                    "四方に手を伸ばしたような雲も",
                    "千切れてたなびく細いグラデーションも",
                    "顔を覗かせた月すらもが",
                    "赤"),
            miyako.deal("$Sは足を血の池に下ろす。",
                    "けれど地面はなく",
                    "伸ばすだけ靴底が沈んでいく"),
            miyako.ask("え？", "え？", "え？"),
            aya.talk("$miyakoも一緒に生まれ変わろう？"),
            miyako.look("足が付かずに戸惑っていた$Sへと",
                    "微笑を浮かべた$ayaの手が伸ばされた"),
            miyako.look("真っ白で無駄な皺のないつるりとした五指が",
                    "掌を向けて$Sへと近づく"),
            miyako.look("彼女の手だけが白だった"),
            miyako.talk("$aya……"),
            miyako.deal("その手を取ろうと$Sも腕を伸ばす"),
            miyako.look("だがその手にはスマートフォンを握り締めていて",
                    "画面は激しく明滅している"),
            kiri.talk("おい！",
                    "$miyako！",
                    "聞こえてるか？"),
            miyako.hear("$kirimura先生の声だった。",
                    "少し喉に詰まったような嗄れた声だけれど",
                    "必死に呼びかけている"),
            miyako.talk("先生……$me"),
            aya.ask("ダレ？"),
            miyako.talk("え？",
                    "ほら", "$kirimura先生だよ。", "美術部顧問の……"),
            miyako.look("$Sを見る$ayaの瞳は虚ろになっていた。",
                    "目玉がなく", "そこにどこまでも深い空虚がある"),
            kiri.talk("そいつは$ayaじゃない！",
                    "さっさと目を覚ませ！",
                    "$meの声を聞け！",
                    "目の前のヤツの言葉を受け入れるな！"),
            aya.ask("$miyako？",
                    "どうして……何故$meを恐れるの？"),
            miyako.look("手だけが白い。",
                    "あとは真っ赤に染まった$ayaだったものが",
                    "「ドウシテ」と口にしながら近寄ってくる"),
            miyako.talk("$aya……じゃないの？"),
            kiri.talk("そうだ！",
                    "信じるな！",
                    "お前は目の前のやつとは親友じゃないんだろ？"),
            miyako.behav("しんゆう。",
                    "とゆっくり口の中で呟いた"),
            miyako.look("目の前の$ayaに似た真っ赤な何かと",
                    "右手のスマートフォンから響いてくる声だけの先生。",
                    "そのどちらもを見てから",
                    "$Sは小さく息を吸い込む"),
            miyako.talk("違う"),
            kiri.talk("そうだ。", "それでいいぞ$miyako"),
            miyako.talk("あんたが違うんだよ！", "先生！"),
            miyako.deal("思い切り叫ぶと",
                    "その勢いのままスマートフォンを投げ捨てた"),
            miyako.look("画面が明滅しながら回転して宙を舞うと",
                    "それは血の海へと落下して小さな悲鳴を上げた"),
            miyako.talk("$aya！"),
            miyako.deal("目の前で溶けかかった巨大なチョコレートの塊みたいになっている$ayaの",
                    "唯一剥き出しになった右手を掴む。",
                    "彼女のピアノを習い続けた細く逞しい指が",
                    "$Sの指をしっかりと掴み返す"),
            miyako.look("その瞬間",
                    "赤い$ayaの瞳が楕円に笑って",
                    "その両端から真っ赤な血のような涙を落とした"),
            aya.talk("$miyako……アリガトウ"),
            miyako.ask("$aya？"),
            miyako.look("手が",
                    "引かれる"),
            miyako.look("$Sは右手の先から$ayaだった真っ赤な塊の中へと吸い込まれていき",
                    "視界から赤に染まった"),
            )

def sc_rescue(w: wd.World):
    miyako, kikyo, kiri, aya = w.miyako, w.kikyo, w.kirimura, w.aya
    return w.scene("救助",
            kiri.talk("$miyako！",
                "大丈夫か？"),
            miyako.hear("それは$kirimuraの声だった"),
            miyako.look("気づくと$Sは真っ赤になった自分の両手を床に突いて四つん這いの状態で", "いた。",
                "顔を上げれば$kirimuraの無精髭面が笑っていて",
                "彼の真っ赤に染まった右手を差し出していた"),
            miyako.deal("一瞬躊躇したが",
                "それを掴んで立ち上がると",
                "ようやくそこが$ayaの部屋の中だと分かる"),
            miyako.look("ただ",
                "ベッドの上にあった白いものは真ん中から破れ",
                "そこから赤い液体が床まで流れ出していた"),
            miyako.look("$Sや先生に付着しているのはその赤だ。",
                "足元も濡れていて",
                "そこから立ち昇る鉄臭さに気持ち悪くなる"),
            miyako.ask("先生", "$ayaは？"),
            miyako.look("だが彼は何も言わず顎でベッドを見るよう促す"),
            miyako.look("ベッドの上には割れた白い卵しか――"),
            miyako.talk("え"),
            miyako.look("そこにあったのはセーラー服だった。",
                "$ayaの着ていたものだろうそれが",
                "赤い液溜まりの上に伸びている"),
            miyako.ask("先生……"),
            kiri.talk("こいつだ"),
            miyako.look("そう言われて見せられたのは",
                "先生の掌大の節くれ立った白い蜘蛛だった。",
                "いや", "蜘蛛とは違う。",
                "足の数こそ多いが", "体が三つの部分に分かれている。",
                "そういうものは虫だと教わっていた"),
            kiri.talk("$spiderと言ってな",
                "翅は無くなってしまっているが",
                "蛾なんだよ"),
            miyako.ask("これが……蛾？"),
            miyako.look("先生の手に握られた団子が三つ並んだようなそれが",
                "もぞもぞと動く"),
            kiri.talk("人の思いを喰らい",
                "羽化する。", "そういう妖魔なんだ"),
            miyako.ask("妖魔って……"),
            kiri.talk("この世とあの世の狭間に棲む存在だ"),
            miyako.look("そう言うと先生は掴んでいたそれを血で濡れた床に投げつけ",
                "靴で踏み潰す。",
                "ブチュ", "という心地悪い音と共に中から緑色の内臓が飛び出すと",
                "鈍い悲鳴を上げてその蛾は絶命した"),
            miyako.ask("それじゃあ$ayaは？"),
            miyako.look("$Sは咄嗟に足元を見る。",
                "転がっていた人型の白いもの。",
                "それが$ayaなのだろうか"),
            kiri.talk("こいつはおそらく$ayaの母親だろう"),
            miyako.ask("え？"),
            kiri.talk("$spiderは若い女性を特に好む。",
                    "思春期の女なんて悩みの塊みたいなものだろう"),
            miyako.look("意味ありげな目線を向けられ", "$Sは先生を睨み返す"),
            kiri.talk("$ayaがいつ$spiderを拾ったのかは知らん。",
                    "だがあの絵を描いた時には既に取り憑かれていたのかもな"),
            miyako.look("そう言った$kirimuraが向けた視線を辿ると",
                    "ベッドの上で血に浮かんでいるセーラー服に行き着く"),
            miyako.talk("$aya！"),
            miyako.hear("何も", "誰も答えない"),
            miyako.talk("$aya！",
                    "$me", "今でも親友だから！", "$ayaのこと", "大切だから！"),
            miyako.move("$Sはベッドの方に駆け出す"),
            miyako.talk("$aya！"),
            miyako.deal("そこに広がる$ayaの残骸を両手で掴み上げると",
                    "ずっしりと重く",
                    "血が滴る"),
            miyako.deal("濡れるのも気にせずに$Sは制服を抱き締めると",
                    "部屋に風が吹き込み",
                    "カーテンを巻き上げる"),
            miyako.look("窓が開いていた"),
            miyako.look("そこに向かって",
                    "$Sの抱えていた制服から",
                    "一匹の蝶が飛ぶ"),
            miyako.look("それはひらひらと",
                    "まるで$Sに手を振っているような揺らぎを見せながら",
                    "窓の外へと消えるようにして出ていく"),
            miyako.talk("$aya……"),
            aya.talk().emphasis("アリガトウ……$miyako"),
            miyako.look("彼女の声を聞いた気がしたが",
                    "振り返ると$kirimuraは分からない様子で$Sのことを見つめていた"),
            )

# episodes
def ep_intro(w: wd.World):
    return (w.chaptertitle("冒頭"),
            sc_redmoon(w),
            )

def ep_chrysalis(w: wd.World):
    return (w.chaptertitle("蛹の少女たち"),
            sc_hermother(w),# NOTE: omit
            sc_boringday(w),# NOTE: omit
            sc_strangeman(w),
            sc_herdrawing(w),
            )

def ep_reasons(w: wd.World):
    return (w.chaptertitle("彼女の理由"),
            sc_herhome(w),
            sc_gotoherroom(w),
            sc_transformed(w),
            sc_othergirls(w),# NOTE: omit
            sc_catchmyheart(w),# NOTE: omit
            sc_crazy(w),# NOTE: omit
            sc_rebirth(w),# NOTE: omit
            sc_mymind(w),
            sc_rescue(w),
            )

# outline
def story_baseinfos(w: wd.World):
    return [
            ("story", story(w), w.miyako, w.aya),
            ]

def story_outlines(w: wd.World):
    return [
            ("story", story(w),
                w.miyako.look(w.aya, w.i.herstatus),
                w.miyako.think(w.aya, w.i.herrefusal),
                w.miyako.look(w.kirimura, w.i.hercause),
                w.miyako.know(w.i.aya_mind),
                True),
            ]

# main
def world():
    w = wd.World("The red emergence")
    w.set_db(cnf.CHARAS, cnf.STAGES, cnf.DAYS, cnf.ITEMS, cnf.INFOS, cnf.FLAGS)
    return w


def story(w: wd.World):
    return (w.maintitle("くれなゐの羽化"),
            ep_intro(w),
            ep_chrysalis(w),
            ep_reasons(w),
            )


def main(): # pragma: no cover
    w = world()
    return w.build(story(w))


if __name__ == '__main__':
    import sys
    sys.exit(main())

