# -*- coding: utf-8 -*-
"""Story: lv1 yusha.
"""
import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '../..'))
sys.path.append('storybuilder')

from storybuilder.builder import world as wd
from src.lv1yusha import config as cnf


# episodes
def ep_intro(w: wd.World):
    outfield = w.stage.field1.insided("町の外")
    forest = w.stage.field1.insided("町の外の森")
    scenes = (
            w.scene("父の背中",
                w.tag.comment("なるべく説明文じゃなく世界観説明"),
                w.hero.look(forest).d("木漏れ日の中に飛び込むようにして", "落ち葉の山を踏み締めた"),
                w.hero.look("back").d("振り返ってみたがまだ父の姿は確認できない"),
                w.hero.go("run", forest, w.day.childhood).d("荒くなる息を何とか押さえようとして口に手を当ててみるが",
                    "すぐに自分の名を呼ぶ父の声が近いと分かり", "走っているのを止めてしまった"),
                w.father.talk(w.hero).t("$he_name", "$heroよ。",
                    "逃げてばかりでは目の前の問題は何も解決せんぞ。",
                    "分かっておるのか？"),
                w.hero.do().d("心臓が破裂しそうになるのを堪えながら太い幹の裏に身を隠すと",
                    "木刀を握る右手に力を込めた。",
                    "何としても一本を取る。",
                    "そうしないと今日の夕ご飯は食べさせないと$dadが言うのだ"),
                w.hero.hear("footsound").d("耳を澄ます。", "革靴が落ち葉を踏み締める音が徐々に大きくなる"),
                w.hero.look().d("木の葉の隙間から角度のついた細い陽光が差し込み一瞬",
                    "$myの右目を掠めた"),
                w.father.talk().t("気配が全然断てておらぬな"),
                w.hero.do().d("その刹那の躊躇いが$myの出足を鈍らせ",
                    "木陰から飛び出した時には既に$dadの振り下ろした木刀が己の右肩へと迫っているところだった"),
                w.hero.talk().t("痛っー！"),
                w.father.talk().t("その程度の痛みで目を閉じるな！",
                    "まだお前は生きているぞ。",
                    "ほら", "剣を構えて応戦するのだ"),
                w.hero.look(w.father).d("右の指先までが痺れてとても木刀を握っていられなかったが",
                    "何とか$dadの言うことに従おうと震える手で構えてみる"),
                w.father.talk().t("どうした$hero！",
                    "これが魔王の配下の一撃なら今ので命まで奪われているぞ！"),
                w.hero.do().d("まだ六歳の$myに大人の剣戟を受け止めきれるはずがない。",
                    "手にしていた木刀は跳ね飛び",
                    "$myは押される勢いのまま真後ろにあった太い樫の樹に強か背中を打ち付けた"),
                w.hero.talk().t("$child_dad", "なんで$meも剣を扱えるようにならないといけないの？",
                    "魔物は全部$child_dadが退治してくれるから$meには必要ないでしょ？"),
                w.hero.do().d("泣きそうになるのを必死で堪えながらそう訴える。",
                    "けれど$myを見る$dadの目は険しい"),
                w.father.talk().t("$meがこの世界の全ての魔物を退治できるなら或いはそういった主張も良かろう。",
                    "だがな", "今ここで百体もの魔物が一斉に襲いかかってきてみろ。",
                    "$meが一体を相手にしている間にお前を誰が守れるというのだ？"),
                w.hero.reply().t("……そんなの"),
                w.father.talk().t("泣いているお前に我が身が守れるのか？",
                    "$na_motherが守れるというのか？"),
                w.hero.talk().d("分かり切った質問に$myは返事すら出来なかった"),
                w.hero.look(w.monster1).d("その父の背後だった。",
                    "黒い影が飛び上がり鋭い五本の爪が閃いて木漏れ日を反射する。"),
                w.hero.do("襲われた", w.i.monster, outfield, w.day.childhood).t("$child_dad！"),
                w.hero.think().d("そう叫びながらも$myは思わず目を閉じていた"),
                w.father.talk().t("$hero。",
                    "誰の心配をしておるのだ？",
                    "相手が一体なら$meは誰にも負けぬわ！"),
                w.hero.hear().d("どさり、という重い音が響いた"),
                w.combine(
                    w.hero.look(w.father, "背中").d("それを耳にしてゆっくりと瞼を持ち上げると",
                        "そこには筋肉の盛り上がった父の偉大な背中がしっかりと$myの方に向けられていた。"),
                    w.hero.think(w.father).d("その強く温かい背中こそ",
                        "自分がずっと憧れて止まないものだと彼は思い出した"),
                    ),
                w.hero.talk().t("$child_dad！"),
                w.father.do("beat", w.monster1).t("さあ飯にしよう。",
                        "家で$na_motherがそろそろ痺れを切らしている頃だ"),
                w.hero.do("助けられた", w.father),
                w.hero.look(w.father).d("$dadは振り向いて",
                        "熊のような髭面を歪ませて笑った"),
                ),
            w.scene("剣の修行",
                w.day.first.explain("歳月が過ぎた").d("あれから十年の歳月が流れた"),
                w.hero.talk(w.bazem).t("手加減はしないで下さい", "$bazem！"),
                w.hero.look(w.bazem).d("木刀を斜に構え",
                    "$myは対峙する神官服の男を睨みつける"),
                w.bazem.reply().t("既に手も足も打ち身だらけになっているのに",
                    "これ以上打ち込んだら君の母親がまた怒鳴り込んでくるよ。",
                    "やる気を見せるのは良いことだがね",
                    "$hero", "時には分を弁えて引くということも立派な判断なのだよ"),
                w.hero.do("剣の練習", w.bazem, w.stage.church, w.day.first).t("それでは何の為の修行ですか！"),
                w.hero.be("十六に成長").d("もう十六にもなったのに",
                    "未だに町の防壁の外に一人で出る許可すら得られず",
                    "英雄$na_fatherの子という名称は単なる揶揄として彼に伸し掛かっていた"),
                w.hero.explain("体格も大きく").d("あの頃より大きくなった自覚はある。",
                    "けれど同世代の中でも小柄な方で",
                    "力比べでは花屋の$na_anabelにすら勝てない"),
                w.hero.think().d("そんな自分を$dadが見たらきっと笑うことだろう"),
                w.hero.ask(w.bazem).t("お願いします！"),
                w.hero.look(w.bazem, "白髪混じり", "微動だにせず隙きがない").d("渋面になった$na_bazemは首を横に振りながらも木刀を構えて見せる。",
                    "額が大きく露出し随分と後退した頭髪には幾らか白いものも混ざる。",
                    "それなのに打ち込む隙きというものが全くない"),
                w.bazem.ask(w.hero).t("どうしたのだ？",
                    "威勢は口だけか？"),
                w.hero.do(w.bazem, "やられる").d("不敵に笑われたが",
                    "それでも$myは打ち出せない。",
                    "その$na_bazemの視線がすっと彼の足元に落とされる"),
                w.hero.think().d("何か？"),
                w.hero.look().d("その一瞬の気取りが",
                    "視界から$bazemの姿を消し去る"),
                w.bazem.talk().t("注意を逸らすな"),
                w.hero.reply().t("すみません！"),
                w.hero.do().d("気づいた時には後頭部を木刀の先で小突かれ",
                    "$myは泣きたくなる"),
                w.hero.talk().t("卑怯ですよ$bazem"),
                w.bazem.reply().t("戦場では常に命を懸けたやり取りが行われておるのに",
                    "卑怯も何も無かろう。",
                    "騙されたなら相手が賢かったということだ。",
                    "それより$hero"),
                w.tag.comment("最近の魔物事情"),
                w.hero.ask().t("何ですか？"),
                w.hero.look(w.bazem).d("教会の裏手の木陰に腰を下ろし",
                    "布で首筋を拭いながら$na_bazemは話し出す"),
                w.bazem.talk(w.hero, w.i.monster, w.flag.increasing).t("お前は最近外に出ていないから知らぬだろうが",
                    "商店に並ぶ品物が少なくなっているとは思わなかったか？"),
                w.hero.remember().t("そう言えば$anabelが自分のところは良いけど何か困っている風なことを言ってたような"),
                w.bazem.talk(w.hero, w.i.case_caravan.flag()).t("もう一月ばかりになる。",
                    "一つとして商隊が町に来ておらぬのだ"),
                w.hero.think().d("商隊とは商人と積荷を守りながら町の間を移動する傭兵たちの部隊ことだ。",
                    "それが来ていないということは積荷も入ってきていないことになる"),
                w.hero.talk().t("海が荒れているという話は聞きませんが"),
                w.hero.think().d(f"この{w.stage.alaban.name}は三日月を大きくしたような島国で",
                        "大半の物資輸送を外洋からの商船に頼っている。",
                        f"港町{w.stage.minan.name}からは三日ほどの距離だが",
                        "この一年ばかり魔物がよく人を襲うので輸送には商隊が付けられるのが常だった"),
                w.bazem.reply().t(f"それが三日前から{w.stage.minan.name}と連絡が取れないと専らの噂だ。",
                        "真偽のほどは知らないが",
                        "昨夜祈りに訪れた旅の者が既に町が滅ぼされていたと言っていた"),
                w.hero.feel().d("その言葉には流石に口元を押さえて黙り込んだ"),
                w.bazem.talk().t("おそらく数日の内には状況が分かるだろう"),
                w.hero.think().d("つまり今現在", "調査部隊が派遣中ということだ。",
                        "そういった王室の表に出ない動きにも",
                        "$na_bazemはよく通じていた"),
                w.bazem.talk(w.hero, w.i.dadlost).t("お前の父が存命ならこのような心配もなかったのだろうがな"),
                w.hero.look(w.bazem).d("そう口にしてしまってから",
                        "$na_bazemは気づいてすぐに「すまぬ」と謝罪する"),
                w.hero.talk(w.bazem, w.i.becomeyusha).t("いいんですよ$bazem。",
                        "$meは大丈夫です。",
                        "それにあの$dadのことだ。",
                        "どこかで元気にやっているかも知れませんから"),
                w.hero.know(w.i.dadlost).d("$myは$dadの姿をこの十年", "見ていない。",
                        "それは$myだけでなくこの町の人間の誰もがそうだった。",
                        "風の噂では魔王退治の時に一緒に奈落と呼ばれる闇の穴に落下したらしい"),
                w.hero.go(w.i.voyage).d("いつかは$dadを探して世界を回りたいと思っていたが",
                        "今の己の技量ではとても叶わぬ願いだと", "自分自身でよく理解していた"),
                w.hero.be(w.i.becomeyusha),
                w.bazem.talk(w.hero, w.flag.strangerogue),
                ),
            w.scene("欠けた家族",
                w.tag.comment("ここで少しだけ家族の現状"),
                w.hero.go(w.stage.myhome, "朝食").t("ただいま"),
                w.mother.reply().t("朝ご飯までに帰る約束はどうしたの？"),
                w.hero.look(w.mother).d("テーブルには既にパンとスープが並べられ",
                    "頬杖を突く仏頂面の母親が入ってきた我が子のことを睨みつけていた"),
                w.hero.talk().t("……ごめん"),
                w.mother.talk().t("別にいいのよ。",
                    "$bazem様には色々と世話になっているし",
                    "何より$meじゃあなたに剣術の指導はしてあげられませんからね。",
                    "そうよ。",
                    "$meじゃ父親の……あの人の代わりは務まらないのよ"),
                w.hero.talk(w.mother, "剣の修行"),
                w.hero.think(w.mother).d("またいつものが始まった。",
                    "$myはそれに大きく頷きながらも「分かったから」と席に就いてパンを千切る"),
                w.hero.talk().t("いただきまーす"),
                w.mother.talk().t("$hero……分かってる？",
                    "$meはただ心配なだけなの。",
                    "あの人みたいにこの町を飛び出てどこか知らない場所で野垂れ死ぬなんてことになったら",
                    "$meは何を支えに生きていけばいいの？"),
                w.mother.explain("髪が長い", "最近目が見えづらい").d("近頃急に髪に白髪が混じり始めた母は",
                    "皺の増えた目を何度も擦る。",
                    "頼まれた針仕事も以前のように沢山はこなせなくなり",
                    "そのうちに別の仕事を考えなければいけないかも知れないと夜な夜な嘆いている"),
                w.hero.think().d("毛布を被りながらその小言を聞かされる度に",
                    "$myは思うのだ。",
                    "自分に本当に必要な技術とは剣術ではなく学問ではないのかと"),
                w.hero.talk(w.mother, "普通の仕事をしてくれても"),
                w.hero.think(w.mother, w.i.becomeyusha),
                w.hero.talk(w.mother, w.i.dadlost),
                w.hero.talk(w.mother, w.i.callhero),
                ),
            w.scene("呼び出し",
                w.tag.comment("ヴェルンは黒幕側だがそれを感じさせない"),
                w.hero.hear().d("ノックの音に最初に気づいたのは$myだった"),
                w.mother.ask().t("どなたかしらね？　はーい"),
                w.hero.look().d("$mamは立ち上がり",
                    "玄関のドアを開ける"),
                w.vern.come(w.stage.myhome).d("そこに立っていたのは詰め襟のかっちりとした制服を着込んだ赤髪の男性だった"),
                w.vern.talk(w.hero, w.i.callhero).t("こちらはオルンガ様のご自宅で宜しいですか？"),
                w.mother.ask().t("ええ、そうですが……貴方は？"),
                w.vern.reply().t("$meはアルアバンの宰相付の秘書官$callmeと申します。",
                    "この度はご子息である$hero様に我が王より直々にお話がありまして",
                    "城へ来ていただくようお願いに来たという次第です"),
                w.hero.ask().t("$meに", "王様が？"),
                w.vern.reply().t("はい。",
                    "出来ましたらその朝食を済ませられたらすぐに支度をしていらしていただきたいのですが",
                    "急でしょうか"),
                w.hero.look(w.mother).d("返答に迷った$myは一度母を見やったが",
                    "彼女は暗い顔をしたまま彼から目を逸らす"),
                w.hero.talk().t("分かりました"),
                w.mother.talk().t("$hero！？"),
                w.hero.talk().t("$mother",
                    "心配しなくても大丈夫だよ。",
                    "$meは$dadとは違う。",
                    "$dadのような英雄にはなれないから"),
                w.hero.think().d("そもそも当時既に町で一番の猛者だった$dadと今の自分では比べるまでもない。",
                    "おそらく何か別の用事で呼ばれただけだろう"),
                w.mother.talk().t("けど……"),
                w.hero.deal(w.i.callhero),
                w.hero.talk(w.mother, "no warry").t("ほんとに大丈夫だから。",
                    "ちょっと話をしてくるだけだよ。",
                    "そうですよね", "$vernさん？"),
                w.vern.reply().t("そのはずですが",
                    "詳しいことは$meには何も知らされておりませんので"),
                w.hero.look().d("$myは席を立ち",
                    "心配そうに見つめる母の肩に手を置いた"),
                w.hero.talk().t("すぐ帰ってくるよ", "$mother"),
                w.mother.talk().t("……"),
                w.hero.look().d("何度か$myは笑い掛けてみたけれど",
                    "$vernが帰ってしまっても一度として母は頷くことはなかった"),
                w.hero.go(w.stage.castle),
                ),
            )
    return [w.chaptertitle("旅立ちまでの序章"),
            *scenes,
            ]


def ep_heros_sun(w: wd.World):
    scenes = (
            w.scene("城へ向かう",
                w.hero.go(w.stage.town).d("朝食を終えるとすぐに一番綺麗な皮のベストを引っ掛け",
                    "アルアバン城へと向かった"),
                w.hero.go(w.stage.castle, "$must"),
                w.hero.go(w.stage.myhome).d("家を出る時に$mamは何度も$myの名を呼んでは振り返らせたが",
                    "そのうちに面倒になり手を挙げるだけになると",
                    "諦めたように最後には「いってらっしゃい」とか細く言ってくれた"),
                w.hero.look(w.stage.town).d("中央通りに出ると",
                    "開店準備をしている人や仕入れ客で商店街にはそれなりに人出があった。",
                    "ただやはり入ってくる物が少ないのか",
                    "どの店の人間も表情が陰っているように$myには思えた"),
                w.anabel.talk().t("$hero", "おはよ"),
                w.hero.look(w.anabel).d("明るい色の髪を二つのおさげにしたそばかすの女性が",
                    "花の余分な葉を落としながら$myに笑顔を向けた"),
                w.hero.talk().t("$anabel", "今日も元気そうだね"),
                w.anabel.talk().t("そんなことないわよ。",
                    f"{w.stage.minan.name}からの荷が入らなくなって",
                    "商店街の人たちピリピリしてるんだから"),
                w.hero.look().d("確かに彼女の言う通り",
                    "会話の端々に入荷のことが話題に上がっているようだった"),
                w.anabel.talk().t("うちはその点",
                    "北山の麓まで行ければ商売にはなるから安心してるけど"),
                w.hero.reply().t("けど以前みたいな魔物が出歩いているようなことになれば",
                    "あんな場所までなんてとても行けなくなる。",
                    "今だって時々一人で出かけているんだろう？"),
                w.anabel.talk().t("$heroよりは力も強いし足も早いのよ？",
                    "それにもし本当にピンチな時には駆けつけてくれるんでしょ？　ねえ"),
                w.hero.look().d("そう言って$na_anabelは顔を見上げてくる。",
                    "彼女の大きなオレンジの瞳が陽光を反射して何だかとても眩しかった"),
                w.hero.talk().t("まだあの日の約束覚えているのかよ。",
                    "あれは勢いで言っただけで"),
                w.anabel.reply().t("分かってるわよ。",
                    "でもね",
                    "今でも$heroが$hefatherさんが帰ってくると信じているのと同じように",
                    "$meも信じてるのよ。", "$heroが$meの英雄になってくれるってね"),
                w.hero.look().d(f"{w.anabel.name}は恥ずかしそうに暫く{w.hero.name}のことを見つめていたが、"),
                w.anabel_mam.talk().t("$anabelちょっと手伝っておくれ"),
                w.anabel.talk().t("はーい"),
                w.hero.look().d("店の奥から彼女の母に呼びつけられると",
                    "舌を出してアカンベェをしてから行ってしまった"),
                w.hero.think().d("何だよ。",
                    "可愛いじゃないか"),
                w.hero.go().d("そんなことを考えてしまった自分が恥ずかしくなり",
                    "$myは城への道を急いだ"),
                w.stage.town.explain("人々の賑わい").d("日は徐々に街全体を明るく照らしていたが",
                    "その半分が墨のような雲に隠され",
                    f"彼の行く手に濃い影を作っていた"),
                w.hero.meet(w.gandof),
                w.gandof.talk(w.hero, w.father),
                w.hero.look("sky", "怪しい雲"),
                w.hero.remember(w.day.dadvoyage),
                w.hero.go("hurry", w.stage.castle),
                ),
            w.scene("城内へ",
                w.hero.look(w.stage.castle, "gate").d("中央街を北側に抜け",
                    "石造りの橋を渡った先に巨大な城門が現れる"),
                w.gatekeeper1.look(w.hero).d("その門扉の前には二人の槍を手にした番兵が立っていたが",
                    f"{w.hero.name}の姿を見るなり表情を険しくした"),
                w.gatekeeper1.ask(w.hero, "用事").t("何用か？"),
                w.hero.reply(w.gatekeeper1, w.i.callhero).t("王様に呼ばれて来ました"),
                w.hero.look().d("それだけ言うと二人は互いの顔を見合わせ、"),
                w.gatekeeper1.talk().t("今確認する。暫くここで待て"),
                w.hero.look().d("一人は脇の小さなドアから中に入り",
                    "残った一人は$myを睨みつけたまま仁王立ちになった"),
                w.hero.do("wait").d("鈍色の甲冑は番兵の胸部と肩",
                    "膝から下を覆う比較的軽装のものだったが",
                    "それでも身につけたまま一日立っているには重そうな装備だと",
                    "$myは感じた"),
                w.day.first.explain().d(f"{w.anabel.name}ならニ、三曲歌い終えるほどの時間が過ぎたろうか"),
                w.hero.deal(w.i.callhero).d("中に確認に向かった一人が戻ってきて、"),
                w.gatekeeper1.talk(w.hero, w.i.herosun).t("失礼しました！"),
                w.hero.hear().d("突然頭を下げられた"),
                w.gatekeeper1.talk().t(f"まさかあの英雄{w.father.name}殿のご子息とは知らず",
                    "大変な無礼を働いたことお許し下さい"),
                w.hero.reply().t("父は父です。",
                    "それよりも許可はいただけたのでしょうか？"),
                w.gatekeeper1.talk().t("はい。",
                    "謁見の間にて王がお待ちです"),
                w.hero.look().d("そう言って再び頭を下げると",
                    "もう一人が「開門！」の声を上げ",
                    "金属製の巨大な門扉が地響きを立てて開いた"),
                w.hero.go(w.stage.castle.insided("城内通路")),
                ),
            w.scene("城内の様子",
                w.combine(
                    w.hero.go(w.stage.castle.insided("ホール")).d("門を抜けて花壇に彩られた小路を進むと",
                        "その先に整然と白い石を積み上げて建てられた王宮が姿を現す"),
                    w.hero.look().d(f"{w.anabel.name}は何度か仕事で中に入ったことがあり",
                        "綺麗とか豪華とか声を湧き立たせて教えてくれたが",
                        "彼はは今初めてそれらを目にしていた"),
                    ),
                w.hero.go().d("アーチになった入り口を潜る"),
                w.hero.talk().t("あぁ……"),
                w.hero.look("物珍しい").d("思わず声が漏れたが",
                    "真っ赤な絨毯が中央の大階段まで続いていて",
                    "見上げれば天井には色硝子の意匠が施されている"),
                w.hero.look().d("大理石の大柱には獅子や虎などの勇猛の象徴が削り出され",
                    f"それらの前に{w.stage.alaban.name}国の紋章である交差した薔薇剣が置かれていた"),
                w.vern.talk(w.hero).t("こういったものに関心がありますか？"),
                w.hero.look(w.vern).d("背後から突然声を掛けられて驚いたが",
                    "$myの家まで用件を伝えに来た秘書官だった。",
                    "確か$vernとかいう名だ"),
                w.hero.talk().t("どうも"),
                w.vern.talk(w.hero, "案内").t("ここは小さな島国です。",
                    "けれどそれだけに歴史はこの世界の中でも古い方になります。",
                    "本王宮は五十年前に再建されたものですが",
                    "その際に以前使われていた建材を流用したと聞いています。",
                    "今$hero殿がご覧になっている多くが",
                    "貴重な文化財でもあるのですよ"),
                w.hero.reply().t("はあ"),
                w.hero.look().d("流暢に語られた知識に面食らいながら$myは生返事をする"),
                w.vern.ask(w.hero, "大事な話").t("特に大丈夫なようでしたらこれより謁見の間にご案内致しますが",
                    "宜しいでしょうか？"),
                w.hero.reply().t("あ、はい。", "お願いします"),
                w.hero.think().d("正直どこをどう行けば目的地に着けるものか皆目分からなかったから",
                    "素直に$vernの申し出を受けた"),
                w.vern.ask(w.hero, w.brokens).t("ではこちらです"),
                w.hero.go(w.vern).d("そう言って歩き出した彼の背に続く"),
                w.hero.look().d("何をしているのか分からない多くの人間がいたが",
                    "大半は騎士や兵士といった武装した者たちで",
                    "彼らの視線はどれも$vernと共に歩く自分を斜に構えて見るものばかりに感じた"),
                w.hero.reply(w.vern),
                w.hero.have(w.brokens),
                w.vern.talk(w.hero, w.stage.castle.insided("謁見の間")).t("大階段を登って二階に行きます。",
                    "普段であれば大広間の先にある大謁見間を使うのですが",
                    "今回は事情があり",
                    "東通路の方の小謁見間の方でお話をされます"),
                w.hero.think().d("その違いがよく理解できない$myはただ「はい」と頷くしかなかった"),
                w.hero.go().d("$vernに続いて絨毯が敷かれた階段を上がると",
                    "左手に折れて通路を進んだ"),
                ),
            w.scene("英雄の子",
                w.hero.meet(w.stage.castle.insided("謁見の間"), w.king, w.day.first).d(f"開けられた窓からは北の{w.stage.abbas.name}に大きな影が落ちている様が見て取れた"),
                w.vern.talk().t("$hero様。", "こちらの部屋で王がお待ちです"),
                w.hero.look().d("他の部屋と見分けが付かない",
                    "特別な意匠もない木製のドアだった。",
                    "$vernは$myの頷きを確認すると",
                    "ドアをノックして「いらっしゃいました」とだけ言った"),
                w.king.talk(w.hero, w.i.herosun).t("通せ"),
                w.hero.hear().d("中から響いたのは男の声だったが", "それを受けて$vernは$myを見やると",
                    "ドアを開けて中に入るようにと促した"),
                w.hero.come(w.stage.castle.insided("謁見の間")).d("緊張気味に$myは部屋に足を踏み入れる"),
                w.hero.look().d("彼が入るとすぐにドアは閉じられ、"),
                w.king.talk(w.hero, w.father).t("よく来たな", "$fatherの子よ"),
                w.hero.look().d("執務用のどっしりとした机の向こう側に座る",
                    "胸元までの白い髭の男性とその両脇に控える制服姿の男たちに出迎えられた"),
                w.hero.ask().t("あ", "その", "どうも初めまして。",
                    "$me、いえ、わたしは$na_fatherの息子$myです"),
                w.hero.hear().d("緊張して上手く話せなかったのだが",
                    "それが気に入らないのか",
                    "王の右側の男が咳払いをする"),
                w.cornel.talk(w.king).t("$meは宰相を務める$myだ。",
                    "本来であればいくら彼の英雄の息子といえど",
                    "このような待遇での謁見は許されておらぬ。",
                    "だが事が事なので",
                    "特例として王自らがこうして面会されているのだ。",
                    "そのことを肝に銘じて口を慎むよう"),
                w.hero.look().d("宰相",
                    "という役割のことは$myにはよく理解出来なかったが",
                    "それでも今自分がいる場所が普通なら入れないところであり",
                    "こうして言葉を交わすことなど普段は許されていない存在が",
                    "王というものなのだと足りない頭に刻み込む"),
                w.king.talk(w.hero).t("して英雄の子よ",
                    "これから宰相が話す事柄についてはまだ誰も知らぬことだ。",
                    "しかし話さぬ訳にもいかぬ。",
                    "それを聞いた上で主に一つ頼みたいことがあってな。",
                    "できれば今ここでそれを拒否せぬと誓ってはくれぬか？"),
                w.hero.think().d("王直々に頼みたい",
                    "それは難しい言葉でいえば勅令と呼ぶらしいことは知っていた。",
                    "つまり今正に$myはその勅令を受けているということになる。",
                    "それはどのような理由が存在しようと拒否することは出来ない",
                    "絶対のものだった"),
                w.hero.reply().t("分かりました"),
                w.hero.look().d("その言葉に満足げに頷くと",
                    "王は宰相を見やり", "用件について説明するよう促した"),
                w.hero.know(w.i.worldinfo, "$not"),
                ),
            w.scene("知らされる事実",
                    w.cornel.do("caugh").d("こほん",
                        "とわざとらしい咳払いをしてから宰相は喋り始める"),
                    w.cornel.talk(w.hero).t("お前でもこの国の商品の多くが",
                        f"{w.stage.minan.name}を経由した外洋からの輸入に頼っていることは承知しておろう"),
                w.hero.reply().d("$bazemが言っていた話だろう", "と$myは直感した"),
                w.cornel.talk().t("それが数日前より入ってこなくなった。",
                    "そこで我々は連絡を取ろうと使者を送ったのだがそれも戻ってこない。",
                    "仕方なく今度は調査隊を組織し現地に向かわせた"),
                w.hero.look().d("宰相は淡々と事実を述べていくが",
                    "王の表情はその間ずっと険しさを漂わせたままだ"),
                w.cornel.talk().t("だが誰一人として戻ってはこなかった。",
                    "調査隊には我が軍の中でもかなりの手練が入っていたが",
                    "先日その者の頭部が何者かにより王宮の前庭に投げ込まれていた"),
                w.hero.feel().d("その様を想像して$myは思わず口を押さえてしまった"),
                w.cornel.talk().t("当初は内内で処理をしようと考えていたのだが",
                    "とてもそのような事態ではないと判断し",
                    "我が王の許可を得て最精鋭の者を調査隊として再び派遣した。",
                    "その中の一人が昨日ボロボロになって戻ってきて報告をしてくれたよ。",
                    f"既に{w.stage.minan.name}は壊滅し",
                    "外は凶暴な魔物で溢れているとな"),
                w.hero.think().d("それは$na_bazemから聞いて想像していた以上のものだった。",
                    "王国軍の精鋭が生き残れないほどの脅威というのは",
                    "自分の父が旅立った十年前の時とは比較にならないほど酷いものだ"),
                w.hero.talk().t("そ、それで$me",
                    "わたしに何を命じられるのでしょうか"),
                w.hero.think().d("力も知恵もない自分のような存在が",
                    "その事態に対して何か出来るとは到底考えられない"),
                w.king.talk().t(f"我が{w.stage.alaban.name}が代々勇者を輩出してきた国だというのは",
                    "知っておろう？"),
                w.hero.hear().d("口を開いたのはずっと黙り込んでいた王の方だった"),
                w.hero.reply().t("は、はい"),
                w.king.talk().t("そなたの父$fatherは勇者の称号を受けてはくれなかったが",
                    "それでもその活躍は周知のように勇者であったと$meは思っておる"),
                w.hero.think().d("そんな話があったとは初耳だ"),
                w.king.talk(w.hero, w.deflag.increasing).t("実は今朝も我が娘$princessが沐浴中に翼を持った魔物に襲われてな。",
                    "大事には至らなかったが",
                    "日に日に奴らの活動は以前のように",
                    "否", "以前よりもずっと脅威的になっておる"),
                w.hero.look(w.cornel).d("そこまで話して王が大きな溜息をつくと",
                    "宰相は自分が「代わりましょうか」と尋ねる。",
                    "だが王は首を振り", "$myに向き直った"),
                w.king.talk(w.hero, w.i.reviveboss).t("噂では魔王が蘇ったとも云われておる"),
                w.hero.know(w.i.reviveboss).d("それは$na_bazemも口にしていた"),
                w.king.ask(w.hero, w.i.case_caravan.deflag()),
                w.hero.know("$not"),
                w.king.ask(w.hero).t("なあ英雄の子よ",
                    "そなたが非力であることは宰相他多くの者からも聞いておる。",
                    "それでもだ。",
                    "勇者としてこの国を", "いや世界を救ってはくれぬか？"),
                w.hero.think().d("勇者。",
                        "その言葉の重さを考えるまでもなく自分には不釣り合いの称号だった。",
                        "もっと相応しい人物は王宮内でなくとも沢山いるだろう。",
                        "それなのに何故自分を"),
                w.hero.ask().t("それは$meが英雄の息子だから", "ですか？"),
                w.cornel.talk().t("なんだその無礼な口の利き方は！"),
                w.hero.look().d(f"{w.cornel.name}はその鋭い目を更にきつくして$myを睨みつけたが",
                        "無視してぎっと王だけを見返し", "改めて口にする"),
                w.hero.ask().t(f"英雄{w.father.name}の子だからですか！？"),
                w.king.reply().t("そうだ"),
                w.hero.look().d("重々しい返事だったが",
                        "王は眉一つ動かさずにそう答えると、"),
                w.king.talk().t("勇者であれば大いなる存在の加護が得られ",
                        "どのような軟弱な若者でも絶対に魔王を打ち倒せると",
                        "そう伝承で云われておる。",
                        "何よりその目。",
                        "お主の父にそっくりではないか。",
                        "それこそが主が勇者の資格を得るに足る器という証拠ぞ"),
                w.hero.look().d("とても七十を前にした齢の気迫ではなかった"),
                w.cornel.ask().t("して返答は？"),
                w.hero.look().d("落ち着いた声に戻った宰相が尋ねるが",
                        "$myは口を開くことが出来ないでいる"),
                w.king.ask().t("返事をするのだ", "英雄の子よ"),
                w.hero.reply().t("……分かりました。",
                        "喜んでお受けします"),
                w.hero.look().d("王の言葉に否とは答えられなかった"),
                w.vern.talk(w.hero, w.i.case_caravan),
                w.hero.ask(w.i.monster),
                w.vern.reply(w.hero, w.i.reviveboss),
                w.hero.talk(w.father, w.i.dadlost),
                ),
            w.scene("勇者誕生",
                w.king.ask(w.hero, w.i.voyage),
                w.king.talk(w.hero, w.i.dadlost),
                w.king.talk(w.hero, w.father),
                w.hero.reply(w.king, w.i.voyage),
                w.hero.go(w.i.voyage, "$must"),
                w.hero.deal(w.king, w.i.bustered).d("こうして$myは勇者となった"),
                w.hero.think().d("だがその事実はまだ部屋にいた王と宰相",
                    "見張りの騎士",
                    "それに部屋の外でずっと控えていた$vern以外は誰も",
                    "知らなかった"),
                w.king.talk("勇者誕生"),
                ),
            )
    return [w.chaptertitle("英雄の息子"),
            *scenes,
            ]


def ep_allies(w: wd.World):
    scenes = (
            w.scene("絡まれる英雄",
                w.hero.go(w.stage.castle.insided("城の外")),
                w.hero.meet(w.marc, w.deflag.strangerogue),
                w.marc.explain("ならず者風"),
                w.marc.ask(w.hero, w.i.herosun),
                w.hero.ask(w.marc, w.father),
                w.marc.do(w.hero, "斬りかかる"),
                w.hero.be("何もできない"),
                w.marc.talk(w.hero, w.i.level),
                w.marc.talk(w.hero, w.i.gatherally),
                w.hero.know(w.marc, w.i.gatherally),
                w.marc.talk(w.stage.bar, w.i.gatherally),
                w.marc.go("out"),
                w.hero.deal(w.i.gatherally),
                ),
            w.scene("酒場にて",
                w.hero.go(w.stage.bar, w.day.first),
                w.stage.bar.explain("薄暗い", "煙草やアルコール臭が漂う"),
                w.hero.look("酒場の人間たち"),
                w.barmaster.ask(w.hero),
                w.hero.reply(w.i.gatherally),
                w.barmaster.talk(w.hero, "無理だな"),
                ),
            w.scene("絡まれる英雄その２",
                w.diana.talk(w.hero),
                w.diana.explain("長身", "酔っぱらい"),
                w.diana.talk(w.hero, w.i.herosun),
                w.hero.talk(w.diana, w.i.herosun),
                w.hero.ask(w.diana, w.i.ally),
                w.diana.talk("laugh"),
                w.diana.talk(w.hero, w.i.level),
                w.hero.talk(w.i.becomeyusha),
                w.diana.ask(w.i.battle, w.hero),
                w.hero.reply("yes"),
                ),
            w.scene("仲間を賭けた戦い",
                w.barmaster.talk("外でやれ"),
                w.hero.go(w.stage.bar.insided("店の外")),
                w.hero.ask(w.diana, w.i.ally),
                w.diana.reply(w.hero, "yes"),
                w.hero.be("動けない"),
                w.diana.do(w.hero, "圧倒"),
                w.diana.talk(w.hero, w.i.level),
                w.hero.think("隙きができる"),
                w.hero.look(w.diana, "つまずく"),
                w.hero.do("attack"),
                w.diana.ask(w.hero, "罠"),
                w.diana.be(w.hero, "win"),
                w.hero.ask("もう一度"),
                w.kult.come("そこまで"),
                ),
            w.scene("仲間"),
                w.maririn.come(),
                w.maririn.ask(w.diana, "なんでそんなこと？"),
                w.diana.reply(w.maririn, "こいつの覚悟を知りたかった"),
                w.maririn.talk("なら充分じゃん"),
                w.maririn.talk(w.hero, w.i.diana_reason),
                w.hero.know(w.i.diana_reason, w.father),
                w.hero.meet(w.diana, w.kult, w.maririn),
                w.hero.talk(w.diana, w.i.voyage),
                w.diana.reply(w.hero, "yes"),
                w.diana.talk("introduce"),
                w.maririn.talk("introduce"),
                w.kult.talk("introduce"),
                w.hero.have(w.diana, w.i.coop),
            )
    return [w.chaptertitle("初めての仲間"),
            *scenes,
            ]


def ep_destruction(w: wd.World):
    scenes = (
            w.scene("街の外",
                w.diana.talk(w.hero, w.stage.tower1),
                w.diana.talk(w.hero, w.i.trial_tower),
                w.hero.look(w.stage.tower1),
                w.hero.know(w.diana, w.stage.tower1),
                w.hero.go(w.stage.tower1, "$must"),
                w.hero.go(w.stage.field1, w.day.first),
                w.hero.go("walk", w.stage.tower1),
                ),
            w.scene("最強の魔物",
                w.hero.meet(w.daemon1),
                w.hero.look(w.daemon1),
                w.daemon1.explain("巨大", "鬼の角", "大きな鎌"),
                w.daemon1.do("kill", w.kult),
                w.maririn.talk("cry", "kult dead"),
                w.diana.do(w.i.battle, w.daemon1),
                w.daemon1.do("kill", w.diana),
                w.hero.be(w.daemon1, w.i.deadly),
                w.hero.be(w.i.massacre),
                w.hero.think("無理だ"),
                ),
            )
    return [w.chaptertitle("全滅"),
            *scenes,
            ]


def ep_anotherhero(w: wd.World):
    scenes = (
            w.scene("もう一人の英雄",
                w.hero.think("恐怖", w.daemon1),
                w.daemon1.ask(w.hero, w.i.herosun),
                w.daemon1.talk(w.hero, "kill"),
                w.daemon1.talk(w.hero, "お前は死ぬようにこの世界はできている", w.flag.crackworld),
                w.hero.do("生き延びる"),
                w.hero.be(w.i.massacre),
                w.hero.go("runaway"),
                w.hero.be(w.stage.field1, w.day.first),
                w.hero.think("死を覚悟"),
                w.hero.do(w.hero99, "rescue"),
                w.hero.look(w.daemon1, "死体"),
                w.hero.look(w.hero99),
                w.hero.look("大量の魔物"),
                w.hero99.talk(w.hero, "一旦逃げるぞ"),
                ),
            w.scene("世界改変",
                w.hero.come(w.stage.field1.insided("洞窟")),
                w.hero.ask(w.hero99),
                w.hero99.reply(w.hero, "レベル９９"),
                w.hero.ask(w.i.level),
                w.hero99.talk(w.i.worldsecret),
                w.hero99.talk(w.deflag.crackworld),
                w.hero.know(w.hero99, w.i.worldsecret),
                w.hero.have(w.hero99, w.i.coop),
                w.hero99.be("vanish"),
                ),
            w.scene("レベル１",
                w.hero.talk(w.hero99),
                w.hero99.talk(w.hero, "本来は存在できない"),
                w.hero99.talk(w.hero, w.i.bug),
                w.hero.ask(w.hero99),
                w.hero99.talk(w.hero, "レベル１から上がらない"),
                ),
            )
    return [w.chaptertitle("もう一人の勇者"),
            *scenes,
            ]


# main
def world():
    w = wd.World("lv1 yusha project")
    w.set_db(cnf.CHARAS,
            cnf.STAGES,
            cnf.DAYS,
            cnf.ITEMS,
            cnf.INFOS,
            cnf.FLAGS,
            )
    return w


def story(w: wd.World):
    return (w.maintitle("レベル１勇者の旅立ち"),
            ep_intro(w),
            ep_heros_sun(w),
            ep_allies(w),
            ep_destruction(w),
            ep_anotherhero(w),
            )


def main(): # pragma: no cover
    w = world()
    return w.build(story(w))


if __name__ == '__main__':
    import sys
    sys.exit(main())

