# -*- coding: utf-8 -*-
"""Story: lv1 yusha.
"""
import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '../..'))
sys.path.append('storybuilder')

from storybuilder.builder import world as wd
from src.lv1yusha import config as cnf


# episodes
def ep_intro(w: wd.World):
    outfield = w.stage.field1.insided("町の外")
    forest = w.stage.field1.insided("町の外の森")
    scenes = (
            w.scene("父の背中",
                w.tag.comment("なるべく説明文じゃなく世界観説明"),
                w.hero.go("run", forest, w.day.childhood).d("荒くなる息を何とか押さえようとして口に手を当てたが",
                    "すぐに自分の名を呼ぶ父の声が近いと分かり", "走っているのを止めてしまった"),
                w.father.talk(w.hero).t("$he_name", "$heroよ。",
                    "逃げてばかりでは目の前の問題は何も解決せんぞ。",
                    "分かっておるのか？"),
                w.hero.do().d("$myは心臓が破裂しそうになるのを堪えながら太い木の裏に身を隠すと",
                    "木刀を握る右手に力を込めた。",
                    "何としても一本を取る。",
                    "そうしないと今日の夕ご飯は食べさせないと$dadが言うのだ"),
                w.hero.hear("footsound").d("耳を澄ます。", "革靴が落ち葉を踏み締める音が徐々に大きくなる"),
                w.hero.look().d("木の葉の隙間から角度のついた細い陽光が差し込むが一瞬",
                    "$myの右目を掠めた"),
                w.father.talk().t("気配が全然断てておらぬな"),
                w.hero.do().d("その一瞬の躊躇いが$myの出足を鈍らせ",
                    "木陰から飛び出した時には既に$dadの振り下ろした木刀が己の右肩へと迫っているところだった"),
                w.hero.talk().t("痛っー！"),
                w.father.talk().t("その程度の痛みで目を閉じるな！",
                    "まだお前は生きているぞ。",
                    "ほら", "剣を構えて応戦するのだ"),
                w.hero.look(w.father).d("右手の指先までが痺れてとても木刀を握っていられなかったが",
                    "何とか$dadの言うことに従おうと震える手で構えてみる"),
                w.father.talk().t("どうした$hero！",
                    "これが魔王の配下の一撃なら今ので命まで奪われているぞ！"),
                w.hero.do().d("まだ六歳の$myに大人の剣戟を受け止めきれるはずがない。",
                    "手にしていた木刀は跳ね飛び",
                    "$myは押される勢いのまま真後ろにあった樫の太い幹に強か背中を打ち付けた"),
                w.hero.talk().t("$child_dad", "なんで$meも剣を扱えるようにならないといけないの？",
                    "魔物は全部$child_dadが退治してくれるから$meには必要ないでしょ？"),
                w.hero.do().d("泣きそうになるのを必死で堪えながらそう訴える。",
                    "けれど$myを見る$dadの目は険しい"),
                w.father.talk().t("$meがこの世界の全ての魔物を退治できるなら或いはそういった主張も良かろう。",
                    "だがな今ここで百体もの魔物が一斉に襲いかかってきてみろ。",
                    "$meが一体を相手にしている間にお前を誰が守れるというのだ？"),
                w.hero.reply().t("……そんなの"),
                w.father.talk().t("泣いているお前に我が身が守れるのか？",
                    "$na_motherが守れるというのか？"),
                w.hero.talk().d("分かり切った質問に$myは返事すら出来なかった"),
                w.hero.look(w.monster1).d("その父の背後だった。",
                    "黒い影が飛び上がり鋭い五本の爪が閃くのが木漏れ陽を反射する。"),
                w.hero.do("襲われた", w.i.monster, outfield, w.day.childhood).t("$child_dad！"),
                w.hero.think().d("そう叫びながらも$myは思わず目を閉じていた"),
                w.father.talk().t("$hero。",
                    "誰の心配をしておるのだ？",
                    "相手が一体なら$meは誰にも負けぬわ！"),
                w.hero.hear().d("どさり、という重い音が響いた"),
                w.combine(
                    w.hero.look(w.father, "背中").d("それを耳にしてゆっくりと瞼を持ち上げると",
                        "そこには筋肉の盛り上がった父の偉大な背中がしっかりと$myの方に向けられていた。"),
                    w.hero.think(w.father).d("その強く温かい背中こそ",
                        "自分がずっと憧れて止まないものだと$myは思い出した"),
                    ),
                w.hero.talk().t("$child_dad！"),
                w.father.do("beat", w.monster1).t("さあ飯にしよう。",
                        "家で$na_motherがそろそろ痺れを切らしている頃だ"),
                w.hero.do("助けられた", w.father),
                w.hero.look(w.father).d("$dadは振り向いて",
                        "熊のような髭面を歪ませて笑った"),
                ),
            w.scene("剣の修行",
                w.day.first.explain("歳月が過ぎた").d("あれから十年の歳月が流れた"),
                w.hero.talk(w.bazem).t("手加減はしないで下さい", "$bazem！"),
                w.hero.look(w.bazem).d("木刀を斜に構え",
                    "$myは対峙する神官服の男を睨みつける"),
                w.bazem.reply().t("既に手も足も打ち身だらけになっているのに",
                    "これ以上打ち込んだら君の母親がまた怒鳴り込んでくるよ。",
                    "やる気を見せるのは良いことだがね",
                    "$hero", "時には分を弁えて引くということも立派な判断なのだよ"),
                w.hero.do("剣の練習", w.bazem, w.stage.church, w.day.first).t("それでは何の為の修行ですか！"),
                w.hero.be("十六に成長").d("もう十六にもなったのに",
                    "未だに町の防壁の外に一人で出る許可すら得られず",
                    "英雄$na_fatherの子という名称は単なる揶揄として彼に伸し掛かっていた"),
                w.hero.explain("体格も大きく").d("あの頃より大きくなった自覚はある。",
                    "けれど同世代の中でも小柄な方で",
                    "力比べでは花屋の$anabelにすら勝てない"),
                w.hero.think().d("そんな自分を$dadが見たらきっと笑うことだろう"),
                w.hero.ask(w.bazem).t("お願いします！"),
                w.hero.look(w.bazem, "白髪混じり", "微動だにせず隙きがない").d("渋面になった$na_bazemは首を横に振りながらも木刀を構えて見せる。",
                    "額が大きく露出し随分と後退した頭髪には幾らか白いものも混ざる。",
                    "それなのに打ち込む隙きというものが全くない"),
                w.bazem.ask(w.hero).t("どうしたのだ？",
                    "威勢は口だけか？"),
                w.hero.do(w.bazem, "やられる").d("不敵に笑われたが",
                    "それでも$myは打ち出せない。",
                    "その$na_bazemの視線がすっと彼の足元に落とされる"),
                w.hero.think().d("何か？"),
                w.hero.look().d("その一瞬の気取りが",
                    "視界から$bazemの姿を消し去る"),
                w.bazem.talk().t("注意を逸らすな"),
                w.hero.reply().t("すみません！"),
                w.hero.do().d("気づいた時には後頭部を木刀の先で小突かれ",
                    "$myは泣きたくなる"),
                w.hero.talk().t("卑怯ですよ$bazem"),
                w.bazem.reply().t("戦場では常に命を懸けたやり取りが行われておるのに",
                    "卑怯も何も無かろう。",
                    "騙されたなら相手が賢かったということだ。",
                    "それより$hero"),
                w.tag.comment("最近の魔物事情"),
                w.hero.ask().t("何ですか？"),
                w.hero.look(w.bazem).d("教会の裏手の木陰に腰を下ろし",
                    "布で首筋を拭いながら$na_bazemは話し出す"),
                w.bazem.talk(w.hero, w.i.monster, w.flag.increasing).t("お前は最近外に出ていないから知らぬだろうが",
                    "商店に並ぶ品物が少なくなっているとは思わなかったか？"),
                w.hero.remember().t("そう言えば$anabelが自分のところは良いけど何か困っている風なことを言ってたような"),
                w.bazem.talk(w.hero, w.i.case_caravan.flag()).t("もう一月ばかりになる。",
                    "一つとして商隊が町に来ておらぬのだ"),
                w.hero.think().d("商隊とは商人と積荷を守りながら町の間を移動する傭兵たちの部隊ことだ。",
                    "それが来ていないということは積荷も入ってきていないことになる"),
                w.hero.talk().t("海が荒れているという話は聞きませんが"),
                w.hero.think().d(f"この{w.stage.alaban.name}は三日月を大きくしたような島国で",
                        "大半の物資輸送を外洋からの商船に頼っている。",
                        f"港町{w.stage.minan.name}からは三日ほどの距離だが",
                        "この一年ばかり魔物がよく人を襲うので輸送には商隊が付けられるのが常だった"),
                w.bazem.reply().t("それが三日前から{w.stage.minan.name}と連絡が取れないと専らの噂だ。",
                        "真偽のほどは知らないが",
                        "昨夜祈りに訪れた旅の者が既に町が滅ぼされていたと言っていた"),
                w.hero.feel().d("その言葉には流石に口元を押さえて黙り込んだ"),
                w.bazem.talk().t("おそらく数日の内には状況が分かるだろう"),
                w.hero.think().d("つまり今現在", "調査部隊が派遣中ということだろう。",
                        "そういった王室の表に出ない動きにも",
                        "$na_bazemはよく通じていた"),
                w.bazem.talk(w.hero, w.i.dadlost).t("お前の父が存命ならこのような心配もなかったのだろうがな"),
                w.hero.look(w.bazem).d("そう口にしてしまってから",
                        "$na_bazemは気づいてすぐに「すまぬ」と謝罪する"),
                w.hero.talk(w.bazem, w.i.becomeyusha).t("いいんですよ$bazem。",
                        "$meは大丈夫です。",
                        "それにあの$dadのことだ。",
                        "どこかで元気にやっているかも知れませんから"),
                w.hero.know(w.i.dadlost).d("$myは$dadの姿をこの十年", "見ていない。",
                        "それは$myだけでなくこの町の人間の誰もがそうだ。",
                        "風の噂では魔王退治の時に一緒に奈落と呼ばれる闇の穴に落下したらしい"),
                w.hero.go(w.i.voyage).d("いつかは$dadを探して世界を回りたいと思っていたが",
                        "今の己の技量ではとても叶わぬ願いだと", "自分自身でよく理解していた"),
                w.hero.be(w.i.becomeyusha),
                w.bazem.talk(w.hero, w.flag.strangerogue),
                ),
            w.scene("欠けた家族",
                w.tag.comment("ここで少しだけ家族の現状"),
                w.hero.go(w.stage.myhome, "朝食").t("ただいま"),
                w.mother.reply().t("朝ご飯までに帰る約束はどうしたの？"),
                w.hero.look(w.mother).d("テーブルには既にパンとスープが並べられ",
                    "頬杖を突く仏頂面の母親が入ってきた我が子のことを睨みつけていた"),
                w.hero.talk().t("……ごめん"),
                w.mother.talk().t("別にいいのよ。",
                    "$bazem様には色々と世話になっているし",
                    "何より$meじゃあなたに剣術の指導はしてあげられませんからね。",
                    "そうよ。",
                    "$meじゃ父親の……あの人の代わりは務まらないのよ"),
                w.hero.talk(w.mother, "剣の修行"),
                w.hero.think(w.mother).d("またいつものが始まった。",
                    "$myはそれに大きく頷きながらも「分かったから」と席に就いてパンを千切る"),
                w.hero.talk().t("いただきまーす"),
                w.mother.talk().t("$hero……分かってる？",
                    "$meはただ心配なだけなの。",
                    "あの人みたいにこの町を飛び出てどこか知らない場所で野垂れ死ぬなんてことになったら",
                    "$meは何を支えに生きていけばいいの？"),
                w.mother.explain("髪が長い", "最近目が見えづらい").d("近頃急に髪に白髪が混じり始めた母は",
                    "皺の増えた目を何度も擦る。",
                    "頼まれた針仕事も以前のように沢山はこなせなくなり",
                    "そのうちに別の仕事を考えなければいけないかも知れないと夜な夜な嘆いている"),
                w.hero.think().d("毛布を被りながらその小言を聞かされる度に",
                    "$myは思うのだ。",
                    "自分に本当に必要な技術とは剣術ではなく学問ではないのかと"),
                w.hero.talk(w.mother, "普通の仕事をしてくれても"),
                w.hero.think(w.mother, w.i.becomeyusha),
                w.hero.talk(w.mother, w.i.dadlost),
                w.hero.talk(w.mother, w.i.callhero),
                ),
            w.scene("呼び出し",
                w.tag.comment("ヴェルンは黒幕側だがそれを感じさせない"),
                w.hero.hear().d("ノックの音に最初に気づいたのは$myだった"),
                w.mother.ask().t("どなたかしらね？　はーい"),
                w.hero.look().d("$motherは立ち上がり",
                    "玄関のドアを開ける"),
                w.vern.come(w.stage.myhome).d("そこに立っていたのは詰め襟のかっちりとした制服を着込んだ赤髪の男性だった"),
                w.vern.talk(w.hero, w.i.callhero).t("こちらはオルンガ様のご自宅で宜しいですか？"),
                w.mother.ask().t("ええ、そうですが……貴方は？"),
                w.vern.reply().t("$meはアルアバンの宰相付の秘書官$callmeと申します。",
                    "この度はご子息である$hero様に我が王より直々にお話がありまして",
                    "城へ来ていただくようお願いに来たという次第です"),
                w.hero.ask().t("$meに", "王様が？"),
                w.vern.reply().t("はい。",
                    "出来ましたらその朝食を済ませられたらすぐに支度をしていらしていただきたいのですが",
                    "急でしょうか"),
                w.hero.look(w.mother).d("返答に迷った$myは一度母を見やったが",
                    "彼女は暗い顔をしたまま彼から目を逸らす"),
                w.hero.talk().t("分かりました"),
                w.mother.talk().t("$hero！？"),
                w.hero.talk().t("$mother",
                    "心配しなくても大丈夫だよ。",
                    "$meは$dadとは違う。",
                    "$dadのような英雄にはなれないから"),
                w.hero.think().d("そもそも当時既に町で一番の猛者だった$dadと今の自分では比べるまでもない。",
                    "おそらく何か別の用事で呼ばれただけだろう"),
                w.mother.talk().t("けど……"),
                w.hero.deal(w.i.callhero),
                w.hero.talk(w.mother, "no warry").t("ほんとに大丈夫だから。",
                    "ちょっと話をしてくるだけだよ。",
                    "そうですよね", "$vernさん？"),
                w.vern.reply().t("そのはずですが",
                    "詳しいことは$meには何も知らされておりませんので"),
                w.hero.look().d("$myは席を立ち",
                    "心配そうに見つめる母の肩に手を置いた"),
                w.hero.talk().t("すぐ帰ってくるよ", "$mother"),
                w.mother.talk().t("……"),
                w.hero.look().d("何度か$myは笑い掛けてみたけれど",
                    "$vernが帰ってしまっても一度として母は頷くことはなかった"),
                w.hero.go(w.stage.castle),
                ),
            )
    return [w.chaptertitle("旅立ちまでの序章"),
            *scenes,
            ]


def ep_heros_sun(w: wd.World):
    scenes = (
            w.scene("城へ向かう",
                w.hero.go(w.stage.castle, "$must"),
                w.hero.go(w.stage.myhome),
                w.hero.look(w.stage.town),
                w.stage.town.explain("人々の賑わい"),
                w.hero.meet(w.gandof),
                w.gandof.talk(w.hero, w.father),
                w.hero.look("sky", "怪しい雲"),
                w.hero.remember(w.day.dadvoyage),
                w.hero.go("hurry", w.stage.castle),
                ),
            w.scene("城内へ",
                w.hero.look(w.stage.castle, "gate"),
                w.gatekeeper1.ask(w.hero, "用事"),
                w.hero.reply(w.gatekeeper1, w.i.callhero),
                w.hero.deal(w.i.callhero),
                w.gatekeeper1.talk(w.hero, w.i.herosun),
                w.hero.go(w.stage.castle.insided("城内通路")),
                ),
            w.scene("城内の様子",
                w.hero.go(w.stage.castle.insided("ホール")),
                w.hero.look("物珍しい"),
                w.hero.look(w.vern),
                w.vern.talk(w.hero, "案内"),
                w.vern.ask(w.hero, "大事な話"),
                w.vern.ask(w.hero, w.brokens),
                w.hero.reply(w.vern),
                w.hero.have(w.brokens),
                w.vern.talk(w.hero, w.stage.castle.insided("謁見の間")),
                ),
            w.scene("英雄の子",
                w.hero.meet(w.stage.castle.insided("謁見の間"), w.king, w.day.first),
                w.king.talk(w.hero, w.i.herosun),
                w.king.talk(w.hero, w.father),
                w.cornel.talk(w.king),
                w.cornel.talk(w.vern),
                w.vern.talk(w.i.worldinfo),
                w.hero.know(w.i.worldinfo, "$not"),
                w.vern.talk(w.i.dadlost),
                ),
            w.scene("知らされる事実",
                w.king.talk(w.hero, w.deflag.increasing),
                w.king.talk(w.hero, w.i.reviveboss),
                w.hero.know(w.i.reviveboss),
                w.king.ask(w.hero, w.i.case_caravan.deflag()),
                w.hero.know("$not"),
                w.vern.talk(w.hero, w.i.case_caravan),
                w.hero.ask(w.i.monster),
                w.vern.reply(w.hero, w.i.reviveboss),
                w.hero.talk(w.father, w.i.dadlost),
                ),
            w.scene("勇者誕生",
                w.king.ask(w.hero, w.i.voyage),
                w.king.talk(w.hero, w.i.dadlost),
                w.king.talk(w.hero, w.father),
                w.hero.reply(w.king, w.i.voyage),
                w.hero.go(w.i.voyage, "$must"),
                w.hero.deal(w.king, w.i.bustered),
                w.king.talk("勇者誕生"),
                ),
            )
    return [w.chaptertitle("英雄の息子"),
            *scenes,
            ]


def ep_allies(w: wd.World):
    scenes = (
            w.scene("絡まれる英雄",
                w.hero.go(w.stage.castle.insided("城の外")),
                w.hero.meet(w.marc, w.deflag.strangerogue),
                w.marc.explain("ならず者風"),
                w.marc.ask(w.hero, w.i.herosun),
                w.hero.ask(w.marc, w.father),
                w.marc.do(w.hero, "斬りかかる"),
                w.hero.be("何もできない"),
                w.marc.talk(w.hero, w.i.level),
                w.marc.talk(w.hero, w.i.gatherally),
                w.hero.know(w.marc, w.i.gatherally),
                w.marc.talk(w.stage.bar, w.i.gatherally),
                w.marc.go("out"),
                w.hero.deal(w.i.gatherally),
                ),
            w.scene("酒場にて",
                w.hero.go(w.stage.bar, w.day.first),
                w.stage.bar.explain("薄暗い", "煙草やアルコール臭が漂う"),
                w.hero.look("酒場の人間たち"),
                w.barmaster.ask(w.hero),
                w.hero.reply(w.i.gatherally),
                w.barmaster.talk(w.hero, "無理だな"),
                ),
            w.scene("絡まれる英雄その２",
                w.diana.talk(w.hero),
                w.diana.explain("長身", "酔っぱらい"),
                w.diana.talk(w.hero, w.i.herosun),
                w.hero.talk(w.diana, w.i.herosun),
                w.hero.ask(w.diana, w.i.ally),
                w.diana.talk("laugh"),
                w.diana.talk(w.hero, w.i.level),
                w.hero.talk(w.i.becomeyusha),
                w.diana.ask(w.i.battle, w.hero),
                w.hero.reply("yes"),
                ),
            w.scene("仲間を賭けた戦い",
                w.barmaster.talk("外でやれ"),
                w.hero.go(w.stage.bar.insided("店の外")),
                w.hero.ask(w.diana, w.i.ally),
                w.diana.reply(w.hero, "yes"),
                w.hero.be("動けない"),
                w.diana.do(w.hero, "圧倒"),
                w.diana.talk(w.hero, w.i.level),
                w.hero.think("隙きができる"),
                w.hero.look(w.diana, "つまずく"),
                w.hero.do("attack"),
                w.diana.ask(w.hero, "罠"),
                w.diana.be(w.hero, "win"),
                w.hero.ask("もう一度"),
                w.kult.come("そこまで"),
                ),
            w.scene("仲間"),
                w.maririn.come(),
                w.maririn.ask(w.diana, "なんでそんなこと？"),
                w.diana.reply(w.maririn, "こいつの覚悟を知りたかった"),
                w.maririn.talk("なら充分じゃん"),
                w.maririn.talk(w.hero, w.i.diana_reason),
                w.hero.know(w.i.diana_reason, w.father),
                w.hero.meet(w.diana, w.kult, w.maririn),
                w.hero.talk(w.diana, w.i.voyage),
                w.diana.reply(w.hero, "yes"),
                w.diana.talk("introduce"),
                w.maririn.talk("introduce"),
                w.kult.talk("introduce"),
                w.hero.have(w.diana, w.i.coop),
            )
    return [w.chaptertitle("初めての仲間"),
            *scenes,
            ]


def ep_destruction(w: wd.World):
    scenes = (
            w.scene("街の外",
                w.diana.talk(w.hero, w.stage.tower1),
                w.diana.talk(w.hero, w.i.trial_tower),
                w.hero.look(w.stage.tower1),
                w.hero.know(w.diana, w.stage.tower1),
                w.hero.go(w.stage.tower1, "$must"),
                w.hero.go(w.stage.field1, w.day.first),
                w.hero.go("walk", w.stage.tower1),
                ),
            w.scene("最強の魔物",
                w.hero.meet(w.daemon1),
                w.hero.look(w.daemon1),
                w.daemon1.explain("巨大", "鬼の角", "大きな鎌"),
                w.daemon1.do("kill", w.kult),
                w.maririn.talk("cry", "kult dead"),
                w.diana.do(w.i.battle, w.daemon1),
                w.daemon1.do("kill", w.diana),
                w.hero.be(w.daemon1, w.i.deadly),
                w.hero.be(w.i.massacre),
                w.hero.think("無理だ"),
                ),
            )
    return [w.chaptertitle("全滅"),
            *scenes,
            ]


def ep_anotherhero(w: wd.World):
    scenes = (
            w.scene("もう一人の英雄",
                w.hero.think("恐怖", w.daemon1),
                w.daemon1.ask(w.hero, w.i.herosun),
                w.daemon1.talk(w.hero, "kill"),
                w.daemon1.talk(w.hero, "お前は死ぬようにこの世界はできている", w.flag.crackworld),
                w.hero.do("生き延びる"),
                w.hero.be(w.i.massacre),
                w.hero.go("runaway"),
                w.hero.be(w.stage.field1, w.day.first),
                w.hero.think("死を覚悟"),
                w.hero.do(w.hero99, "rescue"),
                w.hero.look(w.daemon1, "死体"),
                w.hero.look(w.hero99),
                w.hero.look("大量の魔物"),
                w.hero99.talk(w.hero, "一旦逃げるぞ"),
                ),
            w.scene("世界改変",
                w.hero.come(w.stage.field1.insided("洞窟")),
                w.hero.ask(w.hero99),
                w.hero99.reply(w.hero, "レベル９９"),
                w.hero.ask(w.i.level),
                w.hero99.talk(w.i.worldsecret),
                w.hero99.talk(w.deflag.crackworld),
                w.hero.know(w.hero99, w.i.worldsecret),
                w.hero.have(w.hero99, w.i.coop),
                w.hero99.be("vanish"),
                ),
            w.scene("レベル１",
                w.hero.talk(w.hero99),
                w.hero99.talk(w.hero, "本来は存在できない"),
                w.hero99.talk(w.hero, w.i.bug),
                w.hero.ask(w.hero99),
                w.hero99.talk(w.hero, "レベル１から上がらない"),
                ),
            )
    return [w.chaptertitle("もう一人の勇者"),
            *scenes,
            ]


# main
def world():
    w = wd.World("lv1 yusha project")
    w.set_db(cnf.CHARAS,
            cnf.STAGES,
            cnf.DAYS,
            cnf.ITEMS,
            cnf.INFOS,
            cnf.FLAGS,
            )
    return w


def story(w: wd.World):
    return (w.maintitle("レベル１勇者の旅立ち"),
            ep_intro(w),
            ep_heros_sun(w),
            ep_allies(w),
            ep_destruction(w),
            ep_anotherhero(w),
            )


def main(): # pragma: no cover
    w = world()
    return w.build(story(w))


if __name__ == '__main__':
    import sys
    sys.exit(main())

