# -*- coding: utf-8 -*-
"""Story: the red-chain
"""
import os
import sys
sys.path.append(os.path.join(os.path.dirname(__file__), '../..'))
sys.path.append('storybuilder')

from storybuilder.builder import world as wd
from src.redchain import config as cnf
THM = cnf.THEMES


# episodes
def ep_intro(w: wd.World):
    ma = w.masuda
    scenes = [
            w.scene("車内にて親の愚痴",
                w.tag.comment("三人称の枡田視点のみ"),
                ma.feel().d("やけに車が渋滞しているな",
                    "と感じながらブレーキペダルに足を置いたまま",
                    "スマートフォンを手に取って朝のニュースを確認する。",
                    "ハンドルは左手で支えていたが",
                    "$masudaは右手一本で器用に操作できるような人間ではない。",
                    "仕方なく左手も添えて画面を動かす"),
                ma.be(w.stage.car, w.day.incident),
                ma.look().t("またか"),
                ma.look().d("ＬＩＮＥの通知を開くと案の定母親からで",
                    "それは挨拶とか一言といった類のすぐ見て返信できる類のものではなく",
                    "拝啓から始まる一画面にはとても収まり切らない長い長い文章の塊なのだ"),
                ma.hear().d("$heroは遠くから近づいてくる消防車のサイレンをＢＧＭに",
                    "早く結婚しろだとか家の畑はどうするとかそろそろお前の大好きな新玉葱を送るからいつ家にいるか教えろ",
                    "といった割とどうでもいい話を読み飛ばして",
                    "一番伝えたかったであろう情報を読み取る"),
                ma.hear(w.mam, "祖父母の墓参り").t("ああ、もうそろそろか"),
                ma.think().d("祖母の三回忌と祖父の七回忌が五月の末に迫っていたことを思い出し",
                    "仕事の都合をどうするか考える"),
                ma.look("緊急車両").d("後ろから迫ってきたサイレンの主は車道の中央を何とか抜けていき",
                    "交差点を右折していった。",
                    "二台が連なっていたが",
                    "更に別のサイレンもどこからか響いてくる気がする"),
                ma.think().d("流石にこれは出勤前に取材行くべきか"),
                ma.look("消防車等を見送る"),
                ma.have("上司からのメール").d("そう逡巡したところで",
                    "$na_tanabeからメールが入った"),
                ma.hear().d("それを見ようと右の親指を画面に置こうとすると",
                    "今度は後ろから激しいクラクションだ"),
                ma.look().d("顔を上げて見やれば", "いつの間にか自分の前の車列が十メートル以上先へと進んでしまっている"),
                ma.talk().t("ちょっと待って下さいよ"),
                ma.deal().d("そう言いながら携帯を助手席に放ると",
                    "慌ててハンドルに手をやり", "アクセルに足を乗せる。",
                    "だがその踏み込みが強すぎた。",
                    "耳障りな音を立て車は急発進してしまった"),
                ),
            w.scene("現場取材",
                ma.come(w.stage.thesite).d("現場は古い木造住宅が並ぶ一画で",
                    "野次馬の列を掻き分けて前に出ると",
                    "まだ炎と黒煙塗れのところに消防車が何台も放水しているところだった"),
                ma.ask().t("酷い火事ですね"),
                ma.think().d("口元に手を当てて見ている中年女性の二人組を見て",
                    "それとなく口にする"),
                w.woman1.talk().t("ずっと空き家だったから放火じゃないかって。",
                    "ほら", "この時期になると増えるでしょう",
                    "ちょっとおかしな人が"),
                ma.reply().t("ええ、そうですね"),
                ma.think().d("おかしな人は季節を選ばずに現れるものだと$heroなんかは思うが",
                    "そこは取材の為",
                    "相手に調子を合わせて愛想笑いを返す"),
                w.woman1.talk().t("あら。",
                    "でも救急車来ちゃったわよ"),
                w.woman2.talk().t("ほんとねえ。",
                    "誰かいたのかしら？"),
                ma.look().d("彼女たちの言葉で振り向くと",
                    "確かに一台の白いボディの緊急車両が滑り込むように入ってきて",
                    "消防車の隣に横付けして停車した"),
                w.sugioka.come().t("この時期ホームレスなんかは空き家火災でよく発見されるそうだ"),
                ma.look(w.sugioka, "知人", "学校の先輩").d("$heroの左肩に手を置いて",
                    "その中年女性二人組との間に割り込んで入ってきた長身のニット帽男は",
                    "何度も現場で顔を合わせている地元の新新日報の記者だった"),
                ma.ask().t("$sugi", "いつもながら早いですね"),
                ma.look().d("$heroより頭一つ半ほど大きく",
                    "学生時代にバスケをやっていたという彼は",
                    "初めて目にした彼女たちが頬を赤くする程度には整った目鼻立ちをしている"),
                w.sugioka.talk().t("たまたまですよ。",
                    "$meは人生なんてね",
                    "その殆どが偶然の巡り合わせで出来てるだけだと思ってますから"),
                ma.think().d("これが自分よりも十ほども歳上の人間の表情だろうか",
                    "と羨みたくなるくらいに若々しい笑みでそう言うと、"),
                w.sugioka.ask().t("それで誰が住んでるか分かってるんですか？"),
                ma.look().d("$heroのことは無視して彼女たちに早速インタビューを始めている"),
                ma.think().d("こういう時の咄嗟の判断と行動にこそ人間性が出るのだ",
                    "というチーフの言葉を思い出したが",
                    "所詮タウン誌レベルの情報サイトの記者である自分は",
                    "また彼らからおこぼれでも貰えばいいや的な考えが支配的で",
                    "徐々に火勢が弱まっていくその真っ黒な二階建てをぼんやり眺めて立っていた"),
                ma.hear().d("彼が二人から聞き出している範囲では",
                    "もう十年以上前から空き家になっていて",
                    "最近は野良猫の住処になり周辺住人が役所に苦情を言っていたそうだ"),
                ma.know(w.i.case_fire, w.stage.office),
                ma.think(w.hideko, "何か臭う").d("と「おーい」という大きな声がして",
                    "滝のように水が流れ落ちる建物の入口から二人の消防士が出てくる姿が見えた"),
                w.sugioka.talk().t("やっぱホームレスですかね"),
                ma.look().d("既に二人からの情報は引き出せたらしく",
                    "$heroの隣に腕組みをして立つと",
                    "$na_sugiokaは口元に薄っすら笑みを浮かべながら鋭い視線を投げている"),
                ma.think().d("甘いマスクなのに仕事も出来ておまけに元ミスキャンパスの奥さんまでいる。",
                        "子供は娘が二人で大変だと言いながらも見せられた写真には",
                        "色々な意味で将来有望としか思えない髪の綺麗な二人の女児が笑っていた"),
                ma.think().d("翻って自分はどうだ。",
                        "来年には三十だ。",
                        "仕事もプライベートも",
                        "良いことなんて何も見つけられない日々が過ぎていくだけだった"),
                ma.deal(w.i.interview, w.stage.thesite),
                ma.hear("関係者", w.takamori),
                w.takamori.talk(ma, "空き家だったが"),
                ma.hear("人がいたらしい"),
                ma.hear("消防士が無理だと").d("無理だな"),
                ma.look().d("救急車から下りた隊員に向けた消防士の一人の口がそう動いたのが分かったが",
                        "毛布で包まれたその何かは",
                        "救急車へと載せられていく"),
                ma.think().d("てっきりそれで終わりなのかと思ったが",
                        "首を振りながらもその消防隊員は再び建物の中へと戻っていった。"),
                ma.think().d("まだいるのか？"),
                ma.look().d("そんな$heroの心の声に答えるように$na_sugiokaは小さく首を振ると",
                        "携帯電話を手にこの場を離れた。",
                        "どうやら相手は本社のようだ"),
                ma.think().d("自分も連絡すべきだろうか",
                        "と考えながら今一度野次馬の群れを見やる"),
                ma.look().d("多くは主婦か近所の老人たちだったけれど",
                        "その中に一人だけいた赤子を抱いた若い母親が",
                        "突然泣き叫び始めた我が子を必死にあやす姿が目に入り",
                        "生きているだけマシなのかも知れないと",
                        "慰めにもならない思いが浮上した"),
                ),
            w.scene("会社風景",
                    # TODO: 会社の簡単な説明
                ma.talk().t("おはようございます"),
                ma.come().d("時計を見ると既に十一時を回っていたが仕方ない。",
                    "火災現場周辺での聞き込みと写真撮影",
                    "それに加えて事故渋滞に巻き込まれたのだ。",
                    "災難だった",
                    "という以外に言い訳のしようがない"),
                w.tanabe.ask("何だ。",
                    "髪くらい整えてこいよ"),
                ma.hear().d("けれどチーフマネージャーの$tanabeの第一声は相変わらずのダメ出しだった"),
                ma.look().d("その$na_tanabeは元お役所勤務だけあって",
                    "上下かっちりとしたスーツに今日は赤とオレンジのネクタイ",
                    "頭髪は短く刈り揃えられ",
                    "ハーフフレームの眼鏡が曇り一つなく似合っている"),
                ma.come(w.stage.office, w.day.nextday),
                ma.talk(w.tanabe).t("それで一応取材はしてきたんですけど"),
                w.tanabe.talk().t("なんだ？",
                    "また何もお土産ありませんでした",
                    "なんて言うんじゃないだろうな？"),
                ma.think().d("自分が言う前から色々と察する能力に長けている$na_tanabeこそ",
                    "現場に出る取材記者になれば良いのに",
                    "といつも$heroは思うのだ"),
                ma.talk("昨日の火災事件").t("あ、現場で$sugiokaに会いましたよ"),
                w.tanabe.reply().t("へえ。",
                    "あいつが出張ってたんならただの木造家屋の小火じゃなかったんだな？"),
                ma.talk().t("一応消防隊員が中から引っ張り出してましたよ。",
                    "ただ近所のおばさんたちの話じゃ",
                    "もう十年ばかり誰も住んでなかったって"),
                ma.think().d("そういえばあの後もう一度入っていった消防隊員は",
                    "中に何を見つけていたのだろう。",
                    "$na_tanabeに言われて周辺の聞き込みをしていたから",
                    "結局それが何だったのかを確認しないまま会社に来てしまったことを",
                    "今更に思い出した"),
                ma.hear().d("と、急に$na_tanabeが声を上げる"),
                w.tanabe.reply("遺体が二つ出てきたそうだ").t("おい$masu",
                    "仏が二人いたらしい"),
                ma.look().d("$na_tanabeが見ていたのは$newspaperのウェブサイトだった"),
                ma.talk().t("じゃああの時入ってったのは……"),
                w.tanabe.talk().t("なんだよお前",
                    "ちゃんと取材してきたんじゃないのかよ？"),
                ma.talk().t("いやだから",
                    "$tanaに言われて現場離れちゃったから"),
                w.tanabe.talk().t("なんだよそれは。",
                    "ネタ掴み損ねたのは$meのせいだって？"),
                ma.look().d("そういって$na_tanabeは目を細めた"),
                ma.talk().t("えっと、それよりこれ。",
                    "身元不明の女性と思われる遺体が二体って"),
                ma.think().d("誤魔化すように記事のタイトルを読み上げると",
                    "$heroは自分の机から取材用のデジカメを取り出してから",
                    "そのまま再び取材に出かける"),
                w.tanabe.talk().t("おい！",
                        "折角取材した記事はどうするんだ？"),
                ma.go("取材に出かける").t("メールで送りますよ。",
                        "それより今日はお昼外で食べてくるんで",
                        "魚連の弁当はいいっすわ。", "それじゃ"),
                w.tanabe.talk().t("$masu！",
                        "いつも一つ一つ仕事をきっちりやっつけてからにしろとあれほど"),
                ma.go().d("ドアを閉めると$na_tanabeの声は小さくなった"),
                w.miki.talk().t("あら$masu", "またお出かけ？"),
                ma.look().d("そこでちょうど事務員の$mikiと出くわした"),
                ma.look().d("少し明るくしたという髪は右側の後頭部にピンできっちり留められているが",
                        "その項に僅かに後れ毛が見えた。",
                        "三十になったら辞めようかなと言っていたが",
                        "今日もスカートで",
                        "栗色のスーツの胸元に見える白シャツが何とも眩しい"),
                ma.reply().t("$tanaの人使いが荒いんでね"),
                ma.look().d("そう苦笑して見せたが、"),
                w.miki.talk().t("どうせまたちゃんと調べてこなかったとかでしょ？"),
                ma.think().d("彼女には見事に見破られていて",
                        "それでも微笑みながらグーで胸元を軽く小突いてもらえたのが",
                        "$heroの気分とテンションを一気に上げた"),
                ),
            w.scene("現場に向かう",
                ma.come().d("中央通り沿いにあるラーメン屋で軽く昼食を済ませると",
                    "$heroは再び火災があった住宅街へと向かう"),
                ma.look().d("今の会社に拾われてから二年になるが",
                    "新聞記者になるのを辞めたのにこんな記者紛いの仕事を続けているのは",
                    "結局惰性で生きているだけのつまらない人間なんだろうな",
                    "と自己啓発本を幾つか読んでみて$heroは考えるのだが",
                    "目の前の信号が青に変わったのを見て反射的にアクセルを踏み込むようなもので",
                    "人間そうそう自発的には生きていけないものかも知れない",
                    "等と考えながら",
                    "警邏中のパトカーを横目に走っていく"),
                ),
            w.scene("周辺聞き込み",
                ma.come().d("すっかり炭化した二階建ての周辺には",
                    "まだ作業中の消防隊員や警察官が残っていた"),
                ma.look().d("誰かに話が聞けるだろうかと思ってボイスレコーダを片手に歩いていると、"),
                w.takamori.talk().t("おう$masu"),
                ma.look().d("癖の強い髪が帽子から飛び出した警察官が手を挙げて笑った"),
                ma.talk().t("なんだ$taka。",
                    "刑事になって$meに情報流してくれる約束はいつになったら果たせるようになるんだ？"),
                ma.think().d("$takamoriは同じ高校を出た悪友だった。",
                    "中学の頃は陸上の全国大会に出たこともあるらしいが",
                    "何故か刑事になりたいと高校を出てすぐに警察学校に入った。",
                    "あまり成績の良い方じゃなかったが",
                    "いつまでも刑事になれないところを見るとどうもこのままずっとお巡りさんでいるんじゃないだろうかと",
                    "$heroには思える"),
                w.takamori.talk().t("お前だってブン屋として一流になって汚職をバンバン暴いてやるとか息巻いてたあの頃の輝きは",
                    "どこに置き忘れたんだよ"),
                ma.reply().t("そんなこと一度も言った覚えがないぞ"),
                w.takamori.talk().t("そりゃ$meの捏造だからな"),
                ma.look().d("そう言って$na_takamoriは笑う"),
                ma.think().d("学生時代からいい加減な奴だったが",
                    "何かと落ち込みやすい自分はこの悪友の楽観的なところにかなり助けられたのも事実だ"),
                ma.talk().t("ところで警察発表はいつ頃やるんだ？"),
                w.takamori.talk().t("そんなお上の予定なぞ$meが知る訳ないだろう？"),
                ma.talk().t("そりゃそうだよな。",
                    "多少は使える奴に早く昇進してくれ"),
                w.takamori.talk().t("あ、そうだ。",
                    "$masuはどうすんの？", "高校の同窓会"),
                ma.think().d("出欠確認の葉書が着ていたことを思い出したが",
                    "おそらくゴミと資料の山に埋もれてどこかに消えているだろう"),
                w.takamori.talk().t("たまにはそういうの顔出しとかないと",
                    "好き勝手な噂流されて勝手にどこかで野垂れ死んでることにされちまうぞ"),
                ma.reply().t("$takaが適当に話作っといてくれたらいいだろ。",
                    "ＩＴ系の会社で記事書いてるとか何とか"),
                ma.think().d("そう説明しながらも",
                    "自分は何をしているのか表現する言葉の何とも中途半端な具合に頭が痛くなった"),
                w.takamori.talk().t("また今度暇見つけて飲もうぜ。",
                    "そん時はぜひお前んとこの事務員さんも連れてこいよな"),
                ma.look().d("来年結婚を控えた身でありながらニタリとした顔で肩に手を回してそう言うと",
                    "「まあな」という$heroの適当な返事に頷いて現場の警備に戻ってしまった"),
                ma.deal().d("彼と別れてから数人の野次馬に色々と訊いてみたが",
                    "朝手に入れた情報とそう大差ないものしか得られず",
                    "結局夕方に緊急で開かれた記者会見のニュースを見るまで",
                    "この件に関しては何も進展がなかった"),
                ),
            w.scene("出てきた遺体が二つ",
                ma.look().d("何とか本日分の糸川街情報を更新して",
                    "$heroは帰宅準備を整える"),
                ma.think().d("もうすぐ五時になる。",
                    "このくらいのゆったりとした",
                    "少し寂寥感が漂う空気が$heroは好きだった"),
                ma.look().d("上司で実質的な現場の最高責任者の$na_tanabeは役所に提出する報告書の作成に集中しているし",
                    "事務員の$mikiは電卓を叩いているから経理の仕事中だろう"),
                ma.think().d("三人しかいないから",
                    "という訳ではなく",
                    "基本的にみんな私語が少ない。",
                    "現代的な付き合いと言ってしまえばそうなのだろうが",
                    "会社以外で彼らが何をしてるのか",
                    "$heroは尋ねたことすらなかった"),
                ma.come(w.stage.policestation),
                ma.look().d("そんな空間にいつもＢＧＭのように流れているのが",
                    "地元のケーブルテレビだ。",
                    "十年前の市町村合併により一度は消滅の危機に陥ったらしいが",
                    "何だかんだと続けられている。",
                    "今は地元議会の様子が画面に映っていた"),
                ma.look().d("と、それが突然切り替わる"),
                w.tanabe.talk().t("ん？",
                    "おい$masu。", "今日何か市長会見あるとか言ってたか？"),
                ma.reply().t("いえ。",
                    "聞いてたら流石に現場行ってますよ"),
                w.tanabe.talk().t("だよな"),
                ma.look().d("会見場はどうやら地元警察署内の会議室のようだ"),
                w.policechief.talk().t("えー、本日午前七時十三分に通報がありました住宅火災ですが"),
                ma.hear().d("どうやらあの木造住宅火災についての会見のようだった"),
                w.policechief.talk().t("発見された二体の遺体の身元は現時点では分かっておりません。",
                    "元々長らく使われていなかった空き家であり",
                    "現在行方不明者", "あるいは何らかの事件性両面からの捜索を行っております"),
                ma.hear().d("$heroはその会見の言葉を注意深く聞いていた"),
                ma.think().d("捜索を行っている",
                    "ということは既に何らかの目星が付いているが",
                    "まだ発表できる段階ではない", "ということだ"),
                ma.hear().d("そこに", "$takaからのメールが届く"),
                ma.hear("警察発表"),
                ma.think().d("え？"),
                ma.look().d("それを見た$heroは思わず口走っていた"),
                ma.ask(w.sugioka, w.deadbody).t("あの、$tana。",
                    "$hidekoって聞いたことあります？"),
                w.tanabe.reply().t("$hideko？"),
                ma.look().d("すぐに思い当たらなかったようで$na_tanabeは首を傾げたが",
                    "代わりに$na_mikiが答えた"),
                w.miki.talk().t("三十年前ほどに少し有名になった女優さんで同じ名前の方がいらっしゃいましたけど"),
                ma.look().d("突然$mikiが口を開いたので二人とも驚いて彼女を見たが",
                    "「知りませんか？」と返してから",
                    "こう彼女は続けた"),
                w.miki.talk().t("$i_movienameという映画で",
                    "自分一人で出産から子育てまでをした若い女性を演じて主演女優賞を受賞したこともある",
                    "$hidekoのことですよ？"),
                w.sugioka.talk(w.hideko),
                ma.know(w.deadbody, w.hideko),
                ),
            ]
    return [
            w.chaptertitle("焼死体二つ"),
            *scenes,
            ]


def ep_idolyears(w: wd.World):
    ma = w.masuda
    scenes = [
            w.scene("漫画喫茶で",
                ma.look("アイドル時代の資料を持っている人とやり取り"),
                ),
            w.scene("元プロデューサー",
                ma.know(w.h_idol),
                ma.look(w.h_idol, w.i.life),
                ma.come(w.stage.idoloffice, w.day.interview2),
                ma.deal(w.i.interview, "当時を知る人"),
                w.manager.talk(w.h_idol),
                w.manager.talk("辞めてからも付き合いがあった"),
                w.manager.talk("事情があって芸能界引退"),
                ma.know(w.i.retire_business),
                ),
            ]
    return [w.chaptertitle("アイドル時代"),
            *scenes,
            ]


def ep_actoryears(w: wd.World):
    # NOTE: 女優時代の方が知名度があるのでこちらを先に調査
    ma = w.masuda
    scenes = [
            w.scene("彼女の関係者",
                ma.be(w.stage.office),
                ma.deal("関係者を探す電話"),
                ma.ask(w.hideko),
                ma.go(w.stage.tokyo),
                ),
            w.scene("東京へ",
                ma.be(w.stage.train),
                ma.look("webで彼女の情報", w.hideko),
                w.tag.comment("ここで女優時代の基本的情報"),
                ma.know(w.movie),
                ),
            w.scene("同業者の行方",
                ma.come(w.stage.idoloffice),
                ma.hear("元マネージャの行方"),
                ),
            w.scene("同業者の現在",
                ma.know(w.h_actor),
                ma.look(w.h_actor, w.i.life),
                ma.deal(w.i.interview, w.stage.theater, w.day.interview1),
                ma.deal(w.i.interview, "業界人"),
                ma.meet(w.actoress),
                w.actoress.talk(w.h_actor),
                w.actoress.talk("アイドル時代に声かけた"),
                ma.know(w.hideko, w.h_idol),
                ),
            ]
    return [w.chaptertitle("女優時代"),
            *scenes,
            ]


def ep_lateyears(w: wd.World):
    ma = w.masuda
    scenes = [
            w.scene("結局何も分からず",
                ma.come(w.stage.office),
                w.tag.comment("ここで一旦情報まとめ"),
                ma.talk(w.tanabe, "調べた情報"),
                ma.hear(w.tanabe, "彼女の本名"),
                ),
            w.scene("町の人々への聞き込み",
                ma.know(w.h_later),
                ma.have(w.h_later, w.i.life),
                ma.come(w.stage.town, w.day.interview3),
                ma.deal(w.i.interview, w.stage.town),
                ma.know(w.doc),
                ),
            ]
    return [w.chaptertitle("晩年のこと"),
            *scenes,
            ]


def ep_truth(w: wd.World):
    ma = w.masuda
    scenes = [
            w.scene("検死結果",
                ma.come(w.stage.medicals, w.day.interview3),
                ma.know(w.doc),
                ma.meet(w.doc),
                ma.talk(w.doc, w.i.doc_secret),
                ma.hear(w.doc, w.deadbody),
                ma.know(w.anotherbody, w.benio),
                ma.know(w.i.truth),
                ),
            w.scene("火災現場にて",
                ma.come(w.stage.thesite),
                ma.look("再度調査"),
                ma.meet(w.sugioka),
                ),
            w.scene("杉岡と",
                ma.come(w.stage.bar),
                ma.talk(w.sugioka, w.hideko),
                w.sugioka.talk("彼女の男の話"),
                ),
            w.scene("役場の対応",
                ma.come(w.stage.townoffice),
                ma.meet(w.hino),
                ma.hear(w.hino, w.i.deal_deads),
                ),
            w.scene("遺体の果て",
                ma.come(w.stage.temple),
                ma.meet(w.priest),
                ma.hear(w.priest, w.i.deal_deads),
                ma.think(cnf.THEMES["chain"]),
                ),
            ]
    return [w.chaptertitle("彼女の真実"),
            *scenes,
            ]


# main
def world():
    w = wd.World("The red-chain")
    w.set_db(cnf.CHARAS, cnf.STAGES, cnf.DAYS, cnf.ITEMS, cnf.INFOS, cnf.FLAGS)
    return w


def story(w: wd.World):
    return (w.maintitle("紅い繋がり"),
            ep_intro(w),
            ep_idolyears(w),
            ep_actoryears(w),
            ep_lateyears(w),
            ep_truth(w),
            )


def main(): # pragma: no cover
    w = world()
    return w.build(story(w))


if __name__ == '__main__':
    import sys
    sys.exit(main())

